import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import { env } from './config/env.js';
import routes from './app/routes/index.js';
import notFound from './app/middlewares/notFound.js';
import globalErrorHandler from './app/middlewares/globalErrorHandler.js';
import { rateLimit } from './app/middlewares/rateLimit.js';
const app = express();
app.set('trust proxy', 1);
app.use(helmet());
app.use(cors({ origin: env.corsAllowedOrigins }));
app.use(express.json({ limit: '1mb' }));
app.use(rateLimit());
app.use(morgan('dev'));
app.get('/', (_req, res) => res.json({ message: 'CRMS API' }));
app.use('/api/v1', routes);
app.use(notFound);
app.use(globalErrorHandler);
export default app;
