/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `ClientCompany` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.js';
import type * as Prisma from '../internal/prismaNamespace.js';

/**
 * Model ClientCompany
 *
 */
export type ClientCompanyModel =
  runtime.Types.Result.DefaultSelection<Prisma.$ClientCompanyPayload>;

export type AggregateClientCompany = {
  _count: ClientCompanyCountAggregateOutputType | null;
  _avg: ClientCompanyAvgAggregateOutputType | null;
  _sum: ClientCompanySumAggregateOutputType | null;
  _min: ClientCompanyMinAggregateOutputType | null;
  _max: ClientCompanyMaxAggregateOutputType | null;
};

export type ClientCompanyAvgAggregateOutputType = {
  monthlyQuotaHrs: number | null;
};

export type ClientCompanySumAggregateOutputType = {
  monthlyQuotaHrs: number | null;
};

export type ClientCompanyMinAggregateOutputType = {
  id: string | null;
  name: string | null;
  billingTier: string | null;
  monthlyQuotaHrs: number | null;
  timezone: string | null;
  status: string | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type ClientCompanyMaxAggregateOutputType = {
  id: string | null;
  name: string | null;
  billingTier: string | null;
  monthlyQuotaHrs: number | null;
  timezone: string | null;
  status: string | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type ClientCompanyCountAggregateOutputType = {
  id: number;
  name: number;
  billingTier: number;
  monthlyQuotaHrs: number;
  timezone: number;
  status: number;
  createdAt: number;
  updatedAt: number;
  _all: number;
};

export type ClientCompanyAvgAggregateInputType = {
  monthlyQuotaHrs?: true;
};

export type ClientCompanySumAggregateInputType = {
  monthlyQuotaHrs?: true;
};

export type ClientCompanyMinAggregateInputType = {
  id?: true;
  name?: true;
  billingTier?: true;
  monthlyQuotaHrs?: true;
  timezone?: true;
  status?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type ClientCompanyMaxAggregateInputType = {
  id?: true;
  name?: true;
  billingTier?: true;
  monthlyQuotaHrs?: true;
  timezone?: true;
  status?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type ClientCompanyCountAggregateInputType = {
  id?: true;
  name?: true;
  billingTier?: true;
  monthlyQuotaHrs?: true;
  timezone?: true;
  status?: true;
  createdAt?: true;
  updatedAt?: true;
  _all?: true;
};

export type ClientCompanyAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ClientCompany to aggregate.
   */
  where?: Prisma.ClientCompanyWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ClientCompanies to fetch.
   */
  orderBy?:
    Prisma.ClientCompanyOrderByWithRelationInput | Prisma.ClientCompanyOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.ClientCompanyWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ClientCompanies from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ClientCompanies.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned ClientCompanies
   **/
  _count?: true | ClientCompanyCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: ClientCompanyAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: ClientCompanySumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: ClientCompanyMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: ClientCompanyMaxAggregateInputType;
};

export type GetClientCompanyAggregateType<T extends ClientCompanyAggregateArgs> = {
  [P in keyof T & keyof AggregateClientCompany]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateClientCompany[P]>
    : Prisma.GetScalarType<T[P], AggregateClientCompany[P]>;
};

export type ClientCompanyGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.ClientCompanyWhereInput;
  orderBy?:
    | Prisma.ClientCompanyOrderByWithAggregationInput
    | Prisma.ClientCompanyOrderByWithAggregationInput[];
  by: Prisma.ClientCompanyScalarFieldEnum[] | Prisma.ClientCompanyScalarFieldEnum;
  having?: Prisma.ClientCompanyScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: ClientCompanyCountAggregateInputType | true;
  _avg?: ClientCompanyAvgAggregateInputType;
  _sum?: ClientCompanySumAggregateInputType;
  _min?: ClientCompanyMinAggregateInputType;
  _max?: ClientCompanyMaxAggregateInputType;
};

export type ClientCompanyGroupByOutputType = {
  id: string;
  name: string;
  billingTier: string | null;
  monthlyQuotaHrs: number;
  timezone: string;
  status: string;
  createdAt: Date;
  updatedAt: Date;
  _count: ClientCompanyCountAggregateOutputType | null;
  _avg: ClientCompanyAvgAggregateOutputType | null;
  _sum: ClientCompanySumAggregateOutputType | null;
  _min: ClientCompanyMinAggregateOutputType | null;
  _max: ClientCompanyMaxAggregateOutputType | null;
};

export type GetClientCompanyGroupByPayload<T extends ClientCompanyGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<ClientCompanyGroupByOutputType, T['by']> & {
        [P in keyof T & keyof ClientCompanyGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ClientCompanyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ClientCompanyGroupByOutputType[P]>;
      }
    >
  >;

export type ClientCompanyWhereInput = {
  AND?: Prisma.ClientCompanyWhereInput | Prisma.ClientCompanyWhereInput[];
  OR?: Prisma.ClientCompanyWhereInput[];
  NOT?: Prisma.ClientCompanyWhereInput | Prisma.ClientCompanyWhereInput[];
  id?: Prisma.StringFilter<'ClientCompany'> | string;
  name?: Prisma.StringFilter<'ClientCompany'> | string;
  billingTier?: Prisma.StringNullableFilter<'ClientCompany'> | string | null;
  monthlyQuotaHrs?: Prisma.FloatFilter<'ClientCompany'> | number;
  timezone?: Prisma.StringFilter<'ClientCompany'> | string;
  status?: Prisma.StringFilter<'ClientCompany'> | string;
  createdAt?: Prisma.DateTimeFilter<'ClientCompany'> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<'ClientCompany'> | Date | string;
  users?: Prisma.UserListRelationFilter;
  reservations?: Prisma.ReservationListRelationFilter;
  usageLogs?: Prisma.UsageLogListRelationFilter;
};

export type ClientCompanyOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  billingTier?: Prisma.SortOrderInput | Prisma.SortOrder;
  monthlyQuotaHrs?: Prisma.SortOrder;
  timezone?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  users?: Prisma.UserOrderByRelationAggregateInput;
  reservations?: Prisma.ReservationOrderByRelationAggregateInput;
  usageLogs?: Prisma.UsageLogOrderByRelationAggregateInput;
};

export type ClientCompanyWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    AND?: Prisma.ClientCompanyWhereInput | Prisma.ClientCompanyWhereInput[];
    OR?: Prisma.ClientCompanyWhereInput[];
    NOT?: Prisma.ClientCompanyWhereInput | Prisma.ClientCompanyWhereInput[];
    name?: Prisma.StringFilter<'ClientCompany'> | string;
    billingTier?: Prisma.StringNullableFilter<'ClientCompany'> | string | null;
    monthlyQuotaHrs?: Prisma.FloatFilter<'ClientCompany'> | number;
    timezone?: Prisma.StringFilter<'ClientCompany'> | string;
    status?: Prisma.StringFilter<'ClientCompany'> | string;
    createdAt?: Prisma.DateTimeFilter<'ClientCompany'> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<'ClientCompany'> | Date | string;
    users?: Prisma.UserListRelationFilter;
    reservations?: Prisma.ReservationListRelationFilter;
    usageLogs?: Prisma.UsageLogListRelationFilter;
  },
  'id'
>;

export type ClientCompanyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  billingTier?: Prisma.SortOrderInput | Prisma.SortOrder;
  monthlyQuotaHrs?: Prisma.SortOrder;
  timezone?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  _count?: Prisma.ClientCompanyCountOrderByAggregateInput;
  _avg?: Prisma.ClientCompanyAvgOrderByAggregateInput;
  _max?: Prisma.ClientCompanyMaxOrderByAggregateInput;
  _min?: Prisma.ClientCompanyMinOrderByAggregateInput;
  _sum?: Prisma.ClientCompanySumOrderByAggregateInput;
};

export type ClientCompanyScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.ClientCompanyScalarWhereWithAggregatesInput
    | Prisma.ClientCompanyScalarWhereWithAggregatesInput[];
  OR?: Prisma.ClientCompanyScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.ClientCompanyScalarWhereWithAggregatesInput
    | Prisma.ClientCompanyScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<'ClientCompany'> | string;
  name?: Prisma.StringWithAggregatesFilter<'ClientCompany'> | string;
  billingTier?: Prisma.StringNullableWithAggregatesFilter<'ClientCompany'> | string | null;
  monthlyQuotaHrs?: Prisma.FloatWithAggregatesFilter<'ClientCompany'> | number;
  timezone?: Prisma.StringWithAggregatesFilter<'ClientCompany'> | string;
  status?: Prisma.StringWithAggregatesFilter<'ClientCompany'> | string;
  createdAt?: Prisma.DateTimeWithAggregatesFilter<'ClientCompany'> | Date | string;
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<'ClientCompany'> | Date | string;
};

export type ClientCompanyCreateInput = {
  id?: string;
  name: string;
  billingTier?: string | null;
  monthlyQuotaHrs?: number;
  timezone?: string;
  status?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  users?: Prisma.UserCreateNestedManyWithoutCompanyInput;
  reservations?: Prisma.ReservationCreateNestedManyWithoutClientInput;
  usageLogs?: Prisma.UsageLogCreateNestedManyWithoutClientInput;
};

export type ClientCompanyUncheckedCreateInput = {
  id?: string;
  name: string;
  billingTier?: string | null;
  monthlyQuotaHrs?: number;
  timezone?: string;
  status?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  users?: Prisma.UserUncheckedCreateNestedManyWithoutCompanyInput;
  reservations?: Prisma.ReservationUncheckedCreateNestedManyWithoutClientInput;
  usageLogs?: Prisma.UsageLogUncheckedCreateNestedManyWithoutClientInput;
};

export type ClientCompanyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  billingTier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  monthlyQuotaHrs?: Prisma.FloatFieldUpdateOperationsInput | number;
  timezone?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  users?: Prisma.UserUpdateManyWithoutCompanyNestedInput;
  reservations?: Prisma.ReservationUpdateManyWithoutClientNestedInput;
  usageLogs?: Prisma.UsageLogUpdateManyWithoutClientNestedInput;
};

export type ClientCompanyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  billingTier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  monthlyQuotaHrs?: Prisma.FloatFieldUpdateOperationsInput | number;
  timezone?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  users?: Prisma.UserUncheckedUpdateManyWithoutCompanyNestedInput;
  reservations?: Prisma.ReservationUncheckedUpdateManyWithoutClientNestedInput;
  usageLogs?: Prisma.UsageLogUncheckedUpdateManyWithoutClientNestedInput;
};

export type ClientCompanyCreateManyInput = {
  id?: string;
  name: string;
  billingTier?: string | null;
  monthlyQuotaHrs?: number;
  timezone?: string;
  status?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type ClientCompanyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  billingTier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  monthlyQuotaHrs?: Prisma.FloatFieldUpdateOperationsInput | number;
  timezone?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ClientCompanyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  billingTier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  monthlyQuotaHrs?: Prisma.FloatFieldUpdateOperationsInput | number;
  timezone?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ClientCompanyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  billingTier?: Prisma.SortOrder;
  monthlyQuotaHrs?: Prisma.SortOrder;
  timezone?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type ClientCompanyAvgOrderByAggregateInput = {
  monthlyQuotaHrs?: Prisma.SortOrder;
};

export type ClientCompanyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  billingTier?: Prisma.SortOrder;
  monthlyQuotaHrs?: Prisma.SortOrder;
  timezone?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type ClientCompanyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  billingTier?: Prisma.SortOrder;
  monthlyQuotaHrs?: Prisma.SortOrder;
  timezone?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type ClientCompanySumOrderByAggregateInput = {
  monthlyQuotaHrs?: Prisma.SortOrder;
};

export type ClientCompanyScalarRelationFilter = {
  is?: Prisma.ClientCompanyWhereInput;
  isNot?: Prisma.ClientCompanyWhereInput;
};

export type StringFieldUpdateOperationsInput = {
  set?: string;
};

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null;
};

export type FloatFieldUpdateOperationsInput = {
  set?: number;
  increment?: number;
  decrement?: number;
  multiply?: number;
  divide?: number;
};

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string;
};

export type ClientCompanyCreateNestedOneWithoutUsersInput = {
  create?: Prisma.XOR<
    Prisma.ClientCompanyCreateWithoutUsersInput,
    Prisma.ClientCompanyUncheckedCreateWithoutUsersInput
  >;
  connectOrCreate?: Prisma.ClientCompanyCreateOrConnectWithoutUsersInput;
  connect?: Prisma.ClientCompanyWhereUniqueInput;
};

export type ClientCompanyUpdateOneRequiredWithoutUsersNestedInput = {
  create?: Prisma.XOR<
    Prisma.ClientCompanyCreateWithoutUsersInput,
    Prisma.ClientCompanyUncheckedCreateWithoutUsersInput
  >;
  connectOrCreate?: Prisma.ClientCompanyCreateOrConnectWithoutUsersInput;
  upsert?: Prisma.ClientCompanyUpsertWithoutUsersInput;
  connect?: Prisma.ClientCompanyWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.ClientCompanyUpdateToOneWithWhereWithoutUsersInput,
      Prisma.ClientCompanyUpdateWithoutUsersInput
    >,
    Prisma.ClientCompanyUncheckedUpdateWithoutUsersInput
  >;
};

export type ClientCompanyCreateNestedOneWithoutReservationsInput = {
  create?: Prisma.XOR<
    Prisma.ClientCompanyCreateWithoutReservationsInput,
    Prisma.ClientCompanyUncheckedCreateWithoutReservationsInput
  >;
  connectOrCreate?: Prisma.ClientCompanyCreateOrConnectWithoutReservationsInput;
  connect?: Prisma.ClientCompanyWhereUniqueInput;
};

export type ClientCompanyUpdateOneRequiredWithoutReservationsNestedInput = {
  create?: Prisma.XOR<
    Prisma.ClientCompanyCreateWithoutReservationsInput,
    Prisma.ClientCompanyUncheckedCreateWithoutReservationsInput
  >;
  connectOrCreate?: Prisma.ClientCompanyCreateOrConnectWithoutReservationsInput;
  upsert?: Prisma.ClientCompanyUpsertWithoutReservationsInput;
  connect?: Prisma.ClientCompanyWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.ClientCompanyUpdateToOneWithWhereWithoutReservationsInput,
      Prisma.ClientCompanyUpdateWithoutReservationsInput
    >,
    Prisma.ClientCompanyUncheckedUpdateWithoutReservationsInput
  >;
};

export type ClientCompanyCreateNestedOneWithoutUsageLogsInput = {
  create?: Prisma.XOR<
    Prisma.ClientCompanyCreateWithoutUsageLogsInput,
    Prisma.ClientCompanyUncheckedCreateWithoutUsageLogsInput
  >;
  connectOrCreate?: Prisma.ClientCompanyCreateOrConnectWithoutUsageLogsInput;
  connect?: Prisma.ClientCompanyWhereUniqueInput;
};

export type ClientCompanyUpdateOneRequiredWithoutUsageLogsNestedInput = {
  create?: Prisma.XOR<
    Prisma.ClientCompanyCreateWithoutUsageLogsInput,
    Prisma.ClientCompanyUncheckedCreateWithoutUsageLogsInput
  >;
  connectOrCreate?: Prisma.ClientCompanyCreateOrConnectWithoutUsageLogsInput;
  upsert?: Prisma.ClientCompanyUpsertWithoutUsageLogsInput;
  connect?: Prisma.ClientCompanyWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.ClientCompanyUpdateToOneWithWhereWithoutUsageLogsInput,
      Prisma.ClientCompanyUpdateWithoutUsageLogsInput
    >,
    Prisma.ClientCompanyUncheckedUpdateWithoutUsageLogsInput
  >;
};

export type ClientCompanyCreateWithoutUsersInput = {
  id?: string;
  name: string;
  billingTier?: string | null;
  monthlyQuotaHrs?: number;
  timezone?: string;
  status?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  reservations?: Prisma.ReservationCreateNestedManyWithoutClientInput;
  usageLogs?: Prisma.UsageLogCreateNestedManyWithoutClientInput;
};

export type ClientCompanyUncheckedCreateWithoutUsersInput = {
  id?: string;
  name: string;
  billingTier?: string | null;
  monthlyQuotaHrs?: number;
  timezone?: string;
  status?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  reservations?: Prisma.ReservationUncheckedCreateNestedManyWithoutClientInput;
  usageLogs?: Prisma.UsageLogUncheckedCreateNestedManyWithoutClientInput;
};

export type ClientCompanyCreateOrConnectWithoutUsersInput = {
  where: Prisma.ClientCompanyWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.ClientCompanyCreateWithoutUsersInput,
    Prisma.ClientCompanyUncheckedCreateWithoutUsersInput
  >;
};

export type ClientCompanyUpsertWithoutUsersInput = {
  update: Prisma.XOR<
    Prisma.ClientCompanyUpdateWithoutUsersInput,
    Prisma.ClientCompanyUncheckedUpdateWithoutUsersInput
  >;
  create: Prisma.XOR<
    Prisma.ClientCompanyCreateWithoutUsersInput,
    Prisma.ClientCompanyUncheckedCreateWithoutUsersInput
  >;
  where?: Prisma.ClientCompanyWhereInput;
};

export type ClientCompanyUpdateToOneWithWhereWithoutUsersInput = {
  where?: Prisma.ClientCompanyWhereInput;
  data: Prisma.XOR<
    Prisma.ClientCompanyUpdateWithoutUsersInput,
    Prisma.ClientCompanyUncheckedUpdateWithoutUsersInput
  >;
};

export type ClientCompanyUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  billingTier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  monthlyQuotaHrs?: Prisma.FloatFieldUpdateOperationsInput | number;
  timezone?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  reservations?: Prisma.ReservationUpdateManyWithoutClientNestedInput;
  usageLogs?: Prisma.UsageLogUpdateManyWithoutClientNestedInput;
};

export type ClientCompanyUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  billingTier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  monthlyQuotaHrs?: Prisma.FloatFieldUpdateOperationsInput | number;
  timezone?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  reservations?: Prisma.ReservationUncheckedUpdateManyWithoutClientNestedInput;
  usageLogs?: Prisma.UsageLogUncheckedUpdateManyWithoutClientNestedInput;
};

export type ClientCompanyCreateWithoutReservationsInput = {
  id?: string;
  name: string;
  billingTier?: string | null;
  monthlyQuotaHrs?: number;
  timezone?: string;
  status?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  users?: Prisma.UserCreateNestedManyWithoutCompanyInput;
  usageLogs?: Prisma.UsageLogCreateNestedManyWithoutClientInput;
};

export type ClientCompanyUncheckedCreateWithoutReservationsInput = {
  id?: string;
  name: string;
  billingTier?: string | null;
  monthlyQuotaHrs?: number;
  timezone?: string;
  status?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  users?: Prisma.UserUncheckedCreateNestedManyWithoutCompanyInput;
  usageLogs?: Prisma.UsageLogUncheckedCreateNestedManyWithoutClientInput;
};

export type ClientCompanyCreateOrConnectWithoutReservationsInput = {
  where: Prisma.ClientCompanyWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.ClientCompanyCreateWithoutReservationsInput,
    Prisma.ClientCompanyUncheckedCreateWithoutReservationsInput
  >;
};

export type ClientCompanyUpsertWithoutReservationsInput = {
  update: Prisma.XOR<
    Prisma.ClientCompanyUpdateWithoutReservationsInput,
    Prisma.ClientCompanyUncheckedUpdateWithoutReservationsInput
  >;
  create: Prisma.XOR<
    Prisma.ClientCompanyCreateWithoutReservationsInput,
    Prisma.ClientCompanyUncheckedCreateWithoutReservationsInput
  >;
  where?: Prisma.ClientCompanyWhereInput;
};

export type ClientCompanyUpdateToOneWithWhereWithoutReservationsInput = {
  where?: Prisma.ClientCompanyWhereInput;
  data: Prisma.XOR<
    Prisma.ClientCompanyUpdateWithoutReservationsInput,
    Prisma.ClientCompanyUncheckedUpdateWithoutReservationsInput
  >;
};

export type ClientCompanyUpdateWithoutReservationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  billingTier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  monthlyQuotaHrs?: Prisma.FloatFieldUpdateOperationsInput | number;
  timezone?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  users?: Prisma.UserUpdateManyWithoutCompanyNestedInput;
  usageLogs?: Prisma.UsageLogUpdateManyWithoutClientNestedInput;
};

export type ClientCompanyUncheckedUpdateWithoutReservationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  billingTier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  monthlyQuotaHrs?: Prisma.FloatFieldUpdateOperationsInput | number;
  timezone?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  users?: Prisma.UserUncheckedUpdateManyWithoutCompanyNestedInput;
  usageLogs?: Prisma.UsageLogUncheckedUpdateManyWithoutClientNestedInput;
};

export type ClientCompanyCreateWithoutUsageLogsInput = {
  id?: string;
  name: string;
  billingTier?: string | null;
  monthlyQuotaHrs?: number;
  timezone?: string;
  status?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  users?: Prisma.UserCreateNestedManyWithoutCompanyInput;
  reservations?: Prisma.ReservationCreateNestedManyWithoutClientInput;
};

export type ClientCompanyUncheckedCreateWithoutUsageLogsInput = {
  id?: string;
  name: string;
  billingTier?: string | null;
  monthlyQuotaHrs?: number;
  timezone?: string;
  status?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  users?: Prisma.UserUncheckedCreateNestedManyWithoutCompanyInput;
  reservations?: Prisma.ReservationUncheckedCreateNestedManyWithoutClientInput;
};

export type ClientCompanyCreateOrConnectWithoutUsageLogsInput = {
  where: Prisma.ClientCompanyWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.ClientCompanyCreateWithoutUsageLogsInput,
    Prisma.ClientCompanyUncheckedCreateWithoutUsageLogsInput
  >;
};

export type ClientCompanyUpsertWithoutUsageLogsInput = {
  update: Prisma.XOR<
    Prisma.ClientCompanyUpdateWithoutUsageLogsInput,
    Prisma.ClientCompanyUncheckedUpdateWithoutUsageLogsInput
  >;
  create: Prisma.XOR<
    Prisma.ClientCompanyCreateWithoutUsageLogsInput,
    Prisma.ClientCompanyUncheckedCreateWithoutUsageLogsInput
  >;
  where?: Prisma.ClientCompanyWhereInput;
};

export type ClientCompanyUpdateToOneWithWhereWithoutUsageLogsInput = {
  where?: Prisma.ClientCompanyWhereInput;
  data: Prisma.XOR<
    Prisma.ClientCompanyUpdateWithoutUsageLogsInput,
    Prisma.ClientCompanyUncheckedUpdateWithoutUsageLogsInput
  >;
};

export type ClientCompanyUpdateWithoutUsageLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  billingTier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  monthlyQuotaHrs?: Prisma.FloatFieldUpdateOperationsInput | number;
  timezone?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  users?: Prisma.UserUpdateManyWithoutCompanyNestedInput;
  reservations?: Prisma.ReservationUpdateManyWithoutClientNestedInput;
};

export type ClientCompanyUncheckedUpdateWithoutUsageLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  billingTier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  monthlyQuotaHrs?: Prisma.FloatFieldUpdateOperationsInput | number;
  timezone?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  users?: Prisma.UserUncheckedUpdateManyWithoutCompanyNestedInput;
  reservations?: Prisma.ReservationUncheckedUpdateManyWithoutClientNestedInput;
};

/**
 * Count Type ClientCompanyCountOutputType
 */

export type ClientCompanyCountOutputType = {
  users: number;
  reservations: number;
  usageLogs: number;
};

export type ClientCompanyCountOutputTypeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  users?: boolean | ClientCompanyCountOutputTypeCountUsersArgs;
  reservations?: boolean | ClientCompanyCountOutputTypeCountReservationsArgs;
  usageLogs?: boolean | ClientCompanyCountOutputTypeCountUsageLogsArgs;
};

/**
 * ClientCompanyCountOutputType without action
 */
export type ClientCompanyCountOutputTypeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ClientCompanyCountOutputType
   */
  select?: Prisma.ClientCompanyCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * ClientCompanyCountOutputType without action
 */
export type ClientCompanyCountOutputTypeCountUsersArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.UserWhereInput;
};

/**
 * ClientCompanyCountOutputType without action
 */
export type ClientCompanyCountOutputTypeCountReservationsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.ReservationWhereInput;
};

/**
 * ClientCompanyCountOutputType without action
 */
export type ClientCompanyCountOutputTypeCountUsageLogsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.UsageLogWhereInput;
};

export type ClientCompanySelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    name?: boolean;
    billingTier?: boolean;
    monthlyQuotaHrs?: boolean;
    timezone?: boolean;
    status?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    users?: boolean | Prisma.ClientCompany$usersArgs<ExtArgs>;
    reservations?: boolean | Prisma.ClientCompany$reservationsArgs<ExtArgs>;
    usageLogs?: boolean | Prisma.ClientCompany$usageLogsArgs<ExtArgs>;
    _count?: boolean | Prisma.ClientCompanyCountOutputTypeDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['clientCompany']
>;

export type ClientCompanySelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    name?: boolean;
    billingTier?: boolean;
    monthlyQuotaHrs?: boolean;
    timezone?: boolean;
    status?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
  },
  ExtArgs['result']['clientCompany']
>;

export type ClientCompanySelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    name?: boolean;
    billingTier?: boolean;
    monthlyQuotaHrs?: boolean;
    timezone?: boolean;
    status?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
  },
  ExtArgs['result']['clientCompany']
>;

export type ClientCompanySelectScalar = {
  id?: boolean;
  name?: boolean;
  billingTier?: boolean;
  monthlyQuotaHrs?: boolean;
  timezone?: boolean;
  status?: boolean;
  createdAt?: boolean;
  updatedAt?: boolean;
};

export type ClientCompanyOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'name'
  | 'billingTier'
  | 'monthlyQuotaHrs'
  | 'timezone'
  | 'status'
  | 'createdAt'
  | 'updatedAt',
  ExtArgs['result']['clientCompany']
>;
export type ClientCompanyInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  users?: boolean | Prisma.ClientCompany$usersArgs<ExtArgs>;
  reservations?: boolean | Prisma.ClientCompany$reservationsArgs<ExtArgs>;
  usageLogs?: boolean | Prisma.ClientCompany$usageLogsArgs<ExtArgs>;
  _count?: boolean | Prisma.ClientCompanyCountOutputTypeDefaultArgs<ExtArgs>;
};
export type ClientCompanyIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {};
export type ClientCompanyIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {};

export type $ClientCompanyPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'ClientCompany';
  objects: {
    users: Prisma.$UserPayload<ExtArgs>[];
    reservations: Prisma.$ReservationPayload<ExtArgs>[];
    usageLogs: Prisma.$UsageLogPayload<ExtArgs>[];
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      name: string;
      billingTier: string | null;
      monthlyQuotaHrs: number;
      timezone: string;
      status: string;
      createdAt: Date;
      updatedAt: Date;
    },
    ExtArgs['result']['clientCompany']
  >;
  composites: {};
};

export type ClientCompanyGetPayload<
  S extends boolean | null | undefined | ClientCompanyDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$ClientCompanyPayload, S>;

export type ClientCompanyCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<ClientCompanyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: ClientCompanyCountAggregateInputType | true;
};

export interface ClientCompanyDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['ClientCompany'];
    meta: { name: 'ClientCompany' };
  };
  /**
   * Find zero or one ClientCompany that matches the filter.
   * @param {ClientCompanyFindUniqueArgs} args - Arguments to find a ClientCompany
   * @example
   * // Get one ClientCompany
   * const clientCompany = await prisma.clientCompany.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ClientCompanyFindUniqueArgs>(
    args: Prisma.SelectSubset<T, ClientCompanyFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__ClientCompanyClient<
    runtime.Types.Result.GetResult<
      Prisma.$ClientCompanyPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one ClientCompany that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ClientCompanyFindUniqueOrThrowArgs} args - Arguments to find a ClientCompany
   * @example
   * // Get one ClientCompany
   * const clientCompany = await prisma.clientCompany.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ClientCompanyFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, ClientCompanyFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__ClientCompanyClient<
    runtime.Types.Result.GetResult<
      Prisma.$ClientCompanyPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ClientCompany that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientCompanyFindFirstArgs} args - Arguments to find a ClientCompany
   * @example
   * // Get one ClientCompany
   * const clientCompany = await prisma.clientCompany.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ClientCompanyFindFirstArgs>(
    args?: Prisma.SelectSubset<T, ClientCompanyFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__ClientCompanyClient<
    runtime.Types.Result.GetResult<
      Prisma.$ClientCompanyPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ClientCompany that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientCompanyFindFirstOrThrowArgs} args - Arguments to find a ClientCompany
   * @example
   * // Get one ClientCompany
   * const clientCompany = await prisma.clientCompany.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ClientCompanyFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, ClientCompanyFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__ClientCompanyClient<
    runtime.Types.Result.GetResult<
      Prisma.$ClientCompanyPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more ClientCompanies that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientCompanyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ClientCompanies
   * const clientCompanies = await prisma.clientCompany.findMany()
   *
   * // Get first 10 ClientCompanies
   * const clientCompanies = await prisma.clientCompany.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const clientCompanyWithIdOnly = await prisma.clientCompany.findMany({ select: { id: true } })
   *
   */
  findMany<T extends ClientCompanyFindManyArgs>(
    args?: Prisma.SelectSubset<T, ClientCompanyFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ClientCompanyPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >;

  /**
   * Create a ClientCompany.
   * @param {ClientCompanyCreateArgs} args - Arguments to create a ClientCompany.
   * @example
   * // Create one ClientCompany
   * const ClientCompany = await prisma.clientCompany.create({
   *   data: {
   *     // ... data to create a ClientCompany
   *   }
   * })
   *
   */
  create<T extends ClientCompanyCreateArgs>(
    args: Prisma.SelectSubset<T, ClientCompanyCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__ClientCompanyClient<
    runtime.Types.Result.GetResult<
      Prisma.$ClientCompanyPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many ClientCompanies.
   * @param {ClientCompanyCreateManyArgs} args - Arguments to create many ClientCompanies.
   * @example
   * // Create many ClientCompanies
   * const clientCompany = await prisma.clientCompany.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends ClientCompanyCreateManyArgs>(
    args?: Prisma.SelectSubset<T, ClientCompanyCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many ClientCompanies and returns the data saved in the database.
   * @param {ClientCompanyCreateManyAndReturnArgs} args - Arguments to create many ClientCompanies.
   * @example
   * // Create many ClientCompanies
   * const clientCompany = await prisma.clientCompany.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many ClientCompanies and only return the `id`
   * const clientCompanyWithIdOnly = await prisma.clientCompany.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends ClientCompanyCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, ClientCompanyCreateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ClientCompanyPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a ClientCompany.
   * @param {ClientCompanyDeleteArgs} args - Arguments to delete one ClientCompany.
   * @example
   * // Delete one ClientCompany
   * const ClientCompany = await prisma.clientCompany.delete({
   *   where: {
   *     // ... filter to delete one ClientCompany
   *   }
   * })
   *
   */
  delete<T extends ClientCompanyDeleteArgs>(
    args: Prisma.SelectSubset<T, ClientCompanyDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__ClientCompanyClient<
    runtime.Types.Result.GetResult<
      Prisma.$ClientCompanyPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one ClientCompany.
   * @param {ClientCompanyUpdateArgs} args - Arguments to update one ClientCompany.
   * @example
   * // Update one ClientCompany
   * const clientCompany = await prisma.clientCompany.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends ClientCompanyUpdateArgs>(
    args: Prisma.SelectSubset<T, ClientCompanyUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__ClientCompanyClient<
    runtime.Types.Result.GetResult<
      Prisma.$ClientCompanyPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more ClientCompanies.
   * @param {ClientCompanyDeleteManyArgs} args - Arguments to filter ClientCompanies to delete.
   * @example
   * // Delete a few ClientCompanies
   * const { count } = await prisma.clientCompany.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends ClientCompanyDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, ClientCompanyDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ClientCompanies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientCompanyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ClientCompanies
   * const clientCompany = await prisma.clientCompany.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends ClientCompanyUpdateManyArgs>(
    args: Prisma.SelectSubset<T, ClientCompanyUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ClientCompanies and returns the data updated in the database.
   * @param {ClientCompanyUpdateManyAndReturnArgs} args - Arguments to update many ClientCompanies.
   * @example
   * // Update many ClientCompanies
   * const clientCompany = await prisma.clientCompany.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more ClientCompanies and only return the `id`
   * const clientCompanyWithIdOnly = await prisma.clientCompany.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends ClientCompanyUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, ClientCompanyUpdateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ClientCompanyPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one ClientCompany.
   * @param {ClientCompanyUpsertArgs} args - Arguments to update or create a ClientCompany.
   * @example
   * // Update or create a ClientCompany
   * const clientCompany = await prisma.clientCompany.upsert({
   *   create: {
   *     // ... data to create a ClientCompany
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ClientCompany we want to update
   *   }
   * })
   */
  upsert<T extends ClientCompanyUpsertArgs>(
    args: Prisma.SelectSubset<T, ClientCompanyUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__ClientCompanyClient<
    runtime.Types.Result.GetResult<
      Prisma.$ClientCompanyPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of ClientCompanies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientCompanyCountArgs} args - Arguments to filter ClientCompanies to count.
   * @example
   * // Count the number of ClientCompanies
   * const count = await prisma.clientCompany.count({
   *   where: {
   *     // ... the filter for the ClientCompanies we want to count
   *   }
   * })
   **/
  count<T extends ClientCompanyCountArgs>(
    args?: Prisma.Subset<T, ClientCompanyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ClientCompanyCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a ClientCompany.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientCompanyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends ClientCompanyAggregateArgs>(
    args: Prisma.Subset<T, ClientCompanyAggregateArgs>,
  ): Prisma.PrismaPromise<GetClientCompanyAggregateType<T>>;

  /**
   * Group by ClientCompany.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientCompanyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends ClientCompanyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends (Prisma.True extends HasSelectOrTake
      ? { orderBy: ClientCompanyGroupByArgs['orderBy'] }
      : { orderBy?: ClientCompanyGroupByArgs['orderBy'] }),
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends (T['by'] extends never[] ? Prisma.True : Prisma.False),
    InputErrors extends (ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]),
  >(
    args: Prisma.SubsetIntersection<T, ClientCompanyGroupByArgs, OrderByArg> & InputErrors,
  ): {} extends InputErrors ? GetClientCompanyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the ClientCompany model
   */
  readonly fields: ClientCompanyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ClientCompany.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ClientCompanyClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  users<T extends Prisma.ClientCompany$usersArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.ClientCompany$usersArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, 'findMany', GlobalOmitOptions>
    | Null
  >;
  reservations<T extends Prisma.ClientCompany$reservationsArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.ClientCompany$reservationsArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$ReservationPayload<ExtArgs>,
        T,
        'findMany',
        GlobalOmitOptions
      >
    | Null
  >;
  usageLogs<T extends Prisma.ClientCompany$usageLogsArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.ClientCompany$usageLogsArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$UsageLogPayload<ExtArgs>,
        T,
        'findMany',
        GlobalOmitOptions
      >
    | Null
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the ClientCompany model
 */
export interface ClientCompanyFieldRefs {
  readonly id: Prisma.FieldRef<'ClientCompany', 'String'>;
  readonly name: Prisma.FieldRef<'ClientCompany', 'String'>;
  readonly billingTier: Prisma.FieldRef<'ClientCompany', 'String'>;
  readonly monthlyQuotaHrs: Prisma.FieldRef<'ClientCompany', 'Float'>;
  readonly timezone: Prisma.FieldRef<'ClientCompany', 'String'>;
  readonly status: Prisma.FieldRef<'ClientCompany', 'String'>;
  readonly createdAt: Prisma.FieldRef<'ClientCompany', 'DateTime'>;
  readonly updatedAt: Prisma.FieldRef<'ClientCompany', 'DateTime'>;
}

// Custom InputTypes
/**
 * ClientCompany findUnique
 */
export type ClientCompanyFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ClientCompany
   */
  select?: Prisma.ClientCompanySelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ClientCompany
   */
  omit?: Prisma.ClientCompanyOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientCompanyInclude<ExtArgs> | null;
  /**
   * Filter, which ClientCompany to fetch.
   */
  where: Prisma.ClientCompanyWhereUniqueInput;
};

/**
 * ClientCompany findUniqueOrThrow
 */
export type ClientCompanyFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ClientCompany
   */
  select?: Prisma.ClientCompanySelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ClientCompany
   */
  omit?: Prisma.ClientCompanyOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientCompanyInclude<ExtArgs> | null;
  /**
   * Filter, which ClientCompany to fetch.
   */
  where: Prisma.ClientCompanyWhereUniqueInput;
};

/**
 * ClientCompany findFirst
 */
export type ClientCompanyFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ClientCompany
   */
  select?: Prisma.ClientCompanySelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ClientCompany
   */
  omit?: Prisma.ClientCompanyOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientCompanyInclude<ExtArgs> | null;
  /**
   * Filter, which ClientCompany to fetch.
   */
  where?: Prisma.ClientCompanyWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ClientCompanies to fetch.
   */
  orderBy?:
    Prisma.ClientCompanyOrderByWithRelationInput | Prisma.ClientCompanyOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ClientCompanies.
   */
  cursor?: Prisma.ClientCompanyWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ClientCompanies from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ClientCompanies.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ClientCompanies.
   */
  distinct?: Prisma.ClientCompanyScalarFieldEnum | Prisma.ClientCompanyScalarFieldEnum[];
};

/**
 * ClientCompany findFirstOrThrow
 */
export type ClientCompanyFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ClientCompany
   */
  select?: Prisma.ClientCompanySelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ClientCompany
   */
  omit?: Prisma.ClientCompanyOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientCompanyInclude<ExtArgs> | null;
  /**
   * Filter, which ClientCompany to fetch.
   */
  where?: Prisma.ClientCompanyWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ClientCompanies to fetch.
   */
  orderBy?:
    Prisma.ClientCompanyOrderByWithRelationInput | Prisma.ClientCompanyOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ClientCompanies.
   */
  cursor?: Prisma.ClientCompanyWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ClientCompanies from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ClientCompanies.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ClientCompanies.
   */
  distinct?: Prisma.ClientCompanyScalarFieldEnum | Prisma.ClientCompanyScalarFieldEnum[];
};

/**
 * ClientCompany findMany
 */
export type ClientCompanyFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ClientCompany
   */
  select?: Prisma.ClientCompanySelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ClientCompany
   */
  omit?: Prisma.ClientCompanyOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientCompanyInclude<ExtArgs> | null;
  /**
   * Filter, which ClientCompanies to fetch.
   */
  where?: Prisma.ClientCompanyWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ClientCompanies to fetch.
   */
  orderBy?:
    Prisma.ClientCompanyOrderByWithRelationInput | Prisma.ClientCompanyOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing ClientCompanies.
   */
  cursor?: Prisma.ClientCompanyWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ClientCompanies from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ClientCompanies.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ClientCompanies.
   */
  distinct?: Prisma.ClientCompanyScalarFieldEnum | Prisma.ClientCompanyScalarFieldEnum[];
};

/**
 * ClientCompany create
 */
export type ClientCompanyCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ClientCompany
   */
  select?: Prisma.ClientCompanySelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ClientCompany
   */
  omit?: Prisma.ClientCompanyOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientCompanyInclude<ExtArgs> | null;
  /**
   * The data needed to create a ClientCompany.
   */
  data: Prisma.XOR<Prisma.ClientCompanyCreateInput, Prisma.ClientCompanyUncheckedCreateInput>;
};

/**
 * ClientCompany createMany
 */
export type ClientCompanyCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many ClientCompanies.
   */
  data: Prisma.ClientCompanyCreateManyInput | Prisma.ClientCompanyCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * ClientCompany createManyAndReturn
 */
export type ClientCompanyCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ClientCompany
   */
  select?: Prisma.ClientCompanySelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the ClientCompany
   */
  omit?: Prisma.ClientCompanyOmit<ExtArgs> | null;
  /**
   * The data used to create many ClientCompanies.
   */
  data: Prisma.ClientCompanyCreateManyInput | Prisma.ClientCompanyCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * ClientCompany update
 */
export type ClientCompanyUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ClientCompany
   */
  select?: Prisma.ClientCompanySelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ClientCompany
   */
  omit?: Prisma.ClientCompanyOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientCompanyInclude<ExtArgs> | null;
  /**
   * The data needed to update a ClientCompany.
   */
  data: Prisma.XOR<Prisma.ClientCompanyUpdateInput, Prisma.ClientCompanyUncheckedUpdateInput>;
  /**
   * Choose, which ClientCompany to update.
   */
  where: Prisma.ClientCompanyWhereUniqueInput;
};

/**
 * ClientCompany updateMany
 */
export type ClientCompanyUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update ClientCompanies.
   */
  data: Prisma.XOR<
    Prisma.ClientCompanyUpdateManyMutationInput,
    Prisma.ClientCompanyUncheckedUpdateManyInput
  >;
  /**
   * Filter which ClientCompanies to update
   */
  where?: Prisma.ClientCompanyWhereInput;
  /**
   * Limit how many ClientCompanies to update.
   */
  limit?: number;
};

/**
 * ClientCompany updateManyAndReturn
 */
export type ClientCompanyUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ClientCompany
   */
  select?: Prisma.ClientCompanySelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the ClientCompany
   */
  omit?: Prisma.ClientCompanyOmit<ExtArgs> | null;
  /**
   * The data used to update ClientCompanies.
   */
  data: Prisma.XOR<
    Prisma.ClientCompanyUpdateManyMutationInput,
    Prisma.ClientCompanyUncheckedUpdateManyInput
  >;
  /**
   * Filter which ClientCompanies to update
   */
  where?: Prisma.ClientCompanyWhereInput;
  /**
   * Limit how many ClientCompanies to update.
   */
  limit?: number;
};

/**
 * ClientCompany upsert
 */
export type ClientCompanyUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ClientCompany
   */
  select?: Prisma.ClientCompanySelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ClientCompany
   */
  omit?: Prisma.ClientCompanyOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientCompanyInclude<ExtArgs> | null;
  /**
   * The filter to search for the ClientCompany to update in case it exists.
   */
  where: Prisma.ClientCompanyWhereUniqueInput;
  /**
   * In case the ClientCompany found by the `where` argument doesn't exist, create a new ClientCompany with this data.
   */
  create: Prisma.XOR<Prisma.ClientCompanyCreateInput, Prisma.ClientCompanyUncheckedCreateInput>;
  /**
   * In case the ClientCompany was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ClientCompanyUpdateInput, Prisma.ClientCompanyUncheckedUpdateInput>;
};

/**
 * ClientCompany delete
 */
export type ClientCompanyDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ClientCompany
   */
  select?: Prisma.ClientCompanySelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ClientCompany
   */
  omit?: Prisma.ClientCompanyOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientCompanyInclude<ExtArgs> | null;
  /**
   * Filter which ClientCompany to delete.
   */
  where: Prisma.ClientCompanyWhereUniqueInput;
};

/**
 * ClientCompany deleteMany
 */
export type ClientCompanyDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ClientCompanies to delete
   */
  where?: Prisma.ClientCompanyWhereInput;
  /**
   * Limit how many ClientCompanies to delete.
   */
  limit?: number;
};

/**
 * ClientCompany.users
 */
export type ClientCompany$usersArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null;
  where?: Prisma.UserWhereInput;
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[];
  cursor?: Prisma.UserWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[];
};

/**
 * ClientCompany.reservations
 */
export type ClientCompany$reservationsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Reservation
   */
  select?: Prisma.ReservationSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Reservation
   */
  omit?: Prisma.ReservationOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReservationInclude<ExtArgs> | null;
  where?: Prisma.ReservationWhereInput;
  orderBy?:
    Prisma.ReservationOrderByWithRelationInput | Prisma.ReservationOrderByWithRelationInput[];
  cursor?: Prisma.ReservationWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?: Prisma.ReservationScalarFieldEnum | Prisma.ReservationScalarFieldEnum[];
};

/**
 * ClientCompany.usageLogs
 */
export type ClientCompany$usageLogsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UsageLog
   */
  select?: Prisma.UsageLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UsageLog
   */
  omit?: Prisma.UsageLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsageLogInclude<ExtArgs> | null;
  where?: Prisma.UsageLogWhereInput;
  orderBy?: Prisma.UsageLogOrderByWithRelationInput | Prisma.UsageLogOrderByWithRelationInput[];
  cursor?: Prisma.UsageLogWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?: Prisma.UsageLogScalarFieldEnum | Prisma.UsageLogScalarFieldEnum[];
};

/**
 * ClientCompany without action
 */
export type ClientCompanyDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ClientCompany
   */
  select?: Prisma.ClientCompanySelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ClientCompany
   */
  omit?: Prisma.ClientCompanyOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientCompanyInclude<ExtArgs> | null;
};
