/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `ConferenceRoom` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.js';
import type * as Prisma from '../internal/prismaNamespace.js';

/**
 * Model ConferenceRoom
 *
 */
export type ConferenceRoomModel =
  runtime.Types.Result.DefaultSelection<Prisma.$ConferenceRoomPayload>;

export type AggregateConferenceRoom = {
  _count: ConferenceRoomCountAggregateOutputType | null;
  _avg: ConferenceRoomAvgAggregateOutputType | null;
  _sum: ConferenceRoomSumAggregateOutputType | null;
  _min: ConferenceRoomMinAggregateOutputType | null;
  _max: ConferenceRoomMaxAggregateOutputType | null;
};

export type ConferenceRoomAvgAggregateOutputType = {
  capacity: number | null;
  hourlyRate: number | null;
};

export type ConferenceRoomSumAggregateOutputType = {
  capacity: number | null;
  hourlyRate: number | null;
};

export type ConferenceRoomMinAggregateOutputType = {
  id: string | null;
  name: string | null;
  capacity: number | null;
  description: string | null;
  location: string | null;
  hourlyRate: number | null;
  isActive: boolean | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type ConferenceRoomMaxAggregateOutputType = {
  id: string | null;
  name: string | null;
  capacity: number | null;
  description: string | null;
  location: string | null;
  hourlyRate: number | null;
  isActive: boolean | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type ConferenceRoomCountAggregateOutputType = {
  id: number;
  name: number;
  capacity: number;
  equipmentList: number;
  description: number;
  location: number;
  hourlyRate: number;
  isActive: number;
  createdAt: number;
  updatedAt: number;
  _all: number;
};

export type ConferenceRoomAvgAggregateInputType = {
  capacity?: true;
  hourlyRate?: true;
};

export type ConferenceRoomSumAggregateInputType = {
  capacity?: true;
  hourlyRate?: true;
};

export type ConferenceRoomMinAggregateInputType = {
  id?: true;
  name?: true;
  capacity?: true;
  description?: true;
  location?: true;
  hourlyRate?: true;
  isActive?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type ConferenceRoomMaxAggregateInputType = {
  id?: true;
  name?: true;
  capacity?: true;
  description?: true;
  location?: true;
  hourlyRate?: true;
  isActive?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type ConferenceRoomCountAggregateInputType = {
  id?: true;
  name?: true;
  capacity?: true;
  equipmentList?: true;
  description?: true;
  location?: true;
  hourlyRate?: true;
  isActive?: true;
  createdAt?: true;
  updatedAt?: true;
  _all?: true;
};

export type ConferenceRoomAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ConferenceRoom to aggregate.
   */
  where?: Prisma.ConferenceRoomWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ConferenceRooms to fetch.
   */
  orderBy?:
    Prisma.ConferenceRoomOrderByWithRelationInput | Prisma.ConferenceRoomOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.ConferenceRoomWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ConferenceRooms from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ConferenceRooms.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned ConferenceRooms
   **/
  _count?: true | ConferenceRoomCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: ConferenceRoomAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: ConferenceRoomSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: ConferenceRoomMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: ConferenceRoomMaxAggregateInputType;
};

export type GetConferenceRoomAggregateType<T extends ConferenceRoomAggregateArgs> = {
  [P in keyof T & keyof AggregateConferenceRoom]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateConferenceRoom[P]>
    : Prisma.GetScalarType<T[P], AggregateConferenceRoom[P]>;
};

export type ConferenceRoomGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.ConferenceRoomWhereInput;
  orderBy?:
    | Prisma.ConferenceRoomOrderByWithAggregationInput
    | Prisma.ConferenceRoomOrderByWithAggregationInput[];
  by: Prisma.ConferenceRoomScalarFieldEnum[] | Prisma.ConferenceRoomScalarFieldEnum;
  having?: Prisma.ConferenceRoomScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: ConferenceRoomCountAggregateInputType | true;
  _avg?: ConferenceRoomAvgAggregateInputType;
  _sum?: ConferenceRoomSumAggregateInputType;
  _min?: ConferenceRoomMinAggregateInputType;
  _max?: ConferenceRoomMaxAggregateInputType;
};

export type ConferenceRoomGroupByOutputType = {
  id: string;
  name: string;
  capacity: number;
  equipmentList: string[];
  description: string | null;
  location: string | null;
  hourlyRate: number;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  _count: ConferenceRoomCountAggregateOutputType | null;
  _avg: ConferenceRoomAvgAggregateOutputType | null;
  _sum: ConferenceRoomSumAggregateOutputType | null;
  _min: ConferenceRoomMinAggregateOutputType | null;
  _max: ConferenceRoomMaxAggregateOutputType | null;
};

export type GetConferenceRoomGroupByPayload<T extends ConferenceRoomGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<ConferenceRoomGroupByOutputType, T['by']> & {
        [P in keyof T & keyof ConferenceRoomGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ConferenceRoomGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ConferenceRoomGroupByOutputType[P]>;
      }
    >
  >;

export type ConferenceRoomWhereInput = {
  AND?: Prisma.ConferenceRoomWhereInput | Prisma.ConferenceRoomWhereInput[];
  OR?: Prisma.ConferenceRoomWhereInput[];
  NOT?: Prisma.ConferenceRoomWhereInput | Prisma.ConferenceRoomWhereInput[];
  id?: Prisma.StringFilter<'ConferenceRoom'> | string;
  name?: Prisma.StringFilter<'ConferenceRoom'> | string;
  capacity?: Prisma.IntFilter<'ConferenceRoom'> | number;
  equipmentList?: Prisma.StringNullableListFilter<'ConferenceRoom'>;
  description?: Prisma.StringNullableFilter<'ConferenceRoom'> | string | null;
  location?: Prisma.StringNullableFilter<'ConferenceRoom'> | string | null;
  hourlyRate?: Prisma.FloatFilter<'ConferenceRoom'> | number;
  isActive?: Prisma.BoolFilter<'ConferenceRoom'> | boolean;
  createdAt?: Prisma.DateTimeFilter<'ConferenceRoom'> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<'ConferenceRoom'> | Date | string;
  reservations?: Prisma.ReservationListRelationFilter;
  maintenanceSchedules?: Prisma.MaintenanceScheduleListRelationFilter;
};

export type ConferenceRoomOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  capacity?: Prisma.SortOrder;
  equipmentList?: Prisma.SortOrder;
  description?: Prisma.SortOrderInput | Prisma.SortOrder;
  location?: Prisma.SortOrderInput | Prisma.SortOrder;
  hourlyRate?: Prisma.SortOrder;
  isActive?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  reservations?: Prisma.ReservationOrderByRelationAggregateInput;
  maintenanceSchedules?: Prisma.MaintenanceScheduleOrderByRelationAggregateInput;
};

export type ConferenceRoomWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    AND?: Prisma.ConferenceRoomWhereInput | Prisma.ConferenceRoomWhereInput[];
    OR?: Prisma.ConferenceRoomWhereInput[];
    NOT?: Prisma.ConferenceRoomWhereInput | Prisma.ConferenceRoomWhereInput[];
    name?: Prisma.StringFilter<'ConferenceRoom'> | string;
    capacity?: Prisma.IntFilter<'ConferenceRoom'> | number;
    equipmentList?: Prisma.StringNullableListFilter<'ConferenceRoom'>;
    description?: Prisma.StringNullableFilter<'ConferenceRoom'> | string | null;
    location?: Prisma.StringNullableFilter<'ConferenceRoom'> | string | null;
    hourlyRate?: Prisma.FloatFilter<'ConferenceRoom'> | number;
    isActive?: Prisma.BoolFilter<'ConferenceRoom'> | boolean;
    createdAt?: Prisma.DateTimeFilter<'ConferenceRoom'> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<'ConferenceRoom'> | Date | string;
    reservations?: Prisma.ReservationListRelationFilter;
    maintenanceSchedules?: Prisma.MaintenanceScheduleListRelationFilter;
  },
  'id'
>;

export type ConferenceRoomOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  capacity?: Prisma.SortOrder;
  equipmentList?: Prisma.SortOrder;
  description?: Prisma.SortOrderInput | Prisma.SortOrder;
  location?: Prisma.SortOrderInput | Prisma.SortOrder;
  hourlyRate?: Prisma.SortOrder;
  isActive?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  _count?: Prisma.ConferenceRoomCountOrderByAggregateInput;
  _avg?: Prisma.ConferenceRoomAvgOrderByAggregateInput;
  _max?: Prisma.ConferenceRoomMaxOrderByAggregateInput;
  _min?: Prisma.ConferenceRoomMinOrderByAggregateInput;
  _sum?: Prisma.ConferenceRoomSumOrderByAggregateInput;
};

export type ConferenceRoomScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.ConferenceRoomScalarWhereWithAggregatesInput
    | Prisma.ConferenceRoomScalarWhereWithAggregatesInput[];
  OR?: Prisma.ConferenceRoomScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.ConferenceRoomScalarWhereWithAggregatesInput
    | Prisma.ConferenceRoomScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<'ConferenceRoom'> | string;
  name?: Prisma.StringWithAggregatesFilter<'ConferenceRoom'> | string;
  capacity?: Prisma.IntWithAggregatesFilter<'ConferenceRoom'> | number;
  equipmentList?: Prisma.StringNullableListFilter<'ConferenceRoom'>;
  description?: Prisma.StringNullableWithAggregatesFilter<'ConferenceRoom'> | string | null;
  location?: Prisma.StringNullableWithAggregatesFilter<'ConferenceRoom'> | string | null;
  hourlyRate?: Prisma.FloatWithAggregatesFilter<'ConferenceRoom'> | number;
  isActive?: Prisma.BoolWithAggregatesFilter<'ConferenceRoom'> | boolean;
  createdAt?: Prisma.DateTimeWithAggregatesFilter<'ConferenceRoom'> | Date | string;
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<'ConferenceRoom'> | Date | string;
};

export type ConferenceRoomCreateInput = {
  id?: string;
  name: string;
  capacity: number;
  equipmentList?: Prisma.ConferenceRoomCreateequipmentListInput | string[];
  description?: string | null;
  location?: string | null;
  hourlyRate?: number;
  isActive?: boolean;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  reservations?: Prisma.ReservationCreateNestedManyWithoutRoomInput;
  maintenanceSchedules?: Prisma.MaintenanceScheduleCreateNestedManyWithoutRoomInput;
};

export type ConferenceRoomUncheckedCreateInput = {
  id?: string;
  name: string;
  capacity: number;
  equipmentList?: Prisma.ConferenceRoomCreateequipmentListInput | string[];
  description?: string | null;
  location?: string | null;
  hourlyRate?: number;
  isActive?: boolean;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  reservations?: Prisma.ReservationUncheckedCreateNestedManyWithoutRoomInput;
  maintenanceSchedules?: Prisma.MaintenanceScheduleUncheckedCreateNestedManyWithoutRoomInput;
};

export type ConferenceRoomUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  capacity?: Prisma.IntFieldUpdateOperationsInput | number;
  equipmentList?: Prisma.ConferenceRoomUpdateequipmentListInput | string[];
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  hourlyRate?: Prisma.FloatFieldUpdateOperationsInput | number;
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  reservations?: Prisma.ReservationUpdateManyWithoutRoomNestedInput;
  maintenanceSchedules?: Prisma.MaintenanceScheduleUpdateManyWithoutRoomNestedInput;
};

export type ConferenceRoomUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  capacity?: Prisma.IntFieldUpdateOperationsInput | number;
  equipmentList?: Prisma.ConferenceRoomUpdateequipmentListInput | string[];
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  hourlyRate?: Prisma.FloatFieldUpdateOperationsInput | number;
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  reservations?: Prisma.ReservationUncheckedUpdateManyWithoutRoomNestedInput;
  maintenanceSchedules?: Prisma.MaintenanceScheduleUncheckedUpdateManyWithoutRoomNestedInput;
};

export type ConferenceRoomCreateManyInput = {
  id?: string;
  name: string;
  capacity: number;
  equipmentList?: Prisma.ConferenceRoomCreateequipmentListInput | string[];
  description?: string | null;
  location?: string | null;
  hourlyRate?: number;
  isActive?: boolean;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type ConferenceRoomUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  capacity?: Prisma.IntFieldUpdateOperationsInput | number;
  equipmentList?: Prisma.ConferenceRoomUpdateequipmentListInput | string[];
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  hourlyRate?: Prisma.FloatFieldUpdateOperationsInput | number;
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ConferenceRoomUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  capacity?: Prisma.IntFieldUpdateOperationsInput | number;
  equipmentList?: Prisma.ConferenceRoomUpdateequipmentListInput | string[];
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  hourlyRate?: Prisma.FloatFieldUpdateOperationsInput | number;
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  isEmpty?: boolean;
};

export type ConferenceRoomCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  capacity?: Prisma.SortOrder;
  equipmentList?: Prisma.SortOrder;
  description?: Prisma.SortOrder;
  location?: Prisma.SortOrder;
  hourlyRate?: Prisma.SortOrder;
  isActive?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type ConferenceRoomAvgOrderByAggregateInput = {
  capacity?: Prisma.SortOrder;
  hourlyRate?: Prisma.SortOrder;
};

export type ConferenceRoomMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  capacity?: Prisma.SortOrder;
  description?: Prisma.SortOrder;
  location?: Prisma.SortOrder;
  hourlyRate?: Prisma.SortOrder;
  isActive?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type ConferenceRoomMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  capacity?: Prisma.SortOrder;
  description?: Prisma.SortOrder;
  location?: Prisma.SortOrder;
  hourlyRate?: Prisma.SortOrder;
  isActive?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type ConferenceRoomSumOrderByAggregateInput = {
  capacity?: Prisma.SortOrder;
  hourlyRate?: Prisma.SortOrder;
};

export type ConferenceRoomScalarRelationFilter = {
  is?: Prisma.ConferenceRoomWhereInput;
  isNot?: Prisma.ConferenceRoomWhereInput;
};

export type ConferenceRoomCreateequipmentListInput = {
  set: string[];
};

export type IntFieldUpdateOperationsInput = {
  set?: number;
  increment?: number;
  decrement?: number;
  multiply?: number;
  divide?: number;
};

export type ConferenceRoomUpdateequipmentListInput = {
  set?: string[];
  push?: string | string[];
};

export type ConferenceRoomCreateNestedOneWithoutReservationsInput = {
  create?: Prisma.XOR<
    Prisma.ConferenceRoomCreateWithoutReservationsInput,
    Prisma.ConferenceRoomUncheckedCreateWithoutReservationsInput
  >;
  connectOrCreate?: Prisma.ConferenceRoomCreateOrConnectWithoutReservationsInput;
  connect?: Prisma.ConferenceRoomWhereUniqueInput;
};

export type ConferenceRoomUpdateOneRequiredWithoutReservationsNestedInput = {
  create?: Prisma.XOR<
    Prisma.ConferenceRoomCreateWithoutReservationsInput,
    Prisma.ConferenceRoomUncheckedCreateWithoutReservationsInput
  >;
  connectOrCreate?: Prisma.ConferenceRoomCreateOrConnectWithoutReservationsInput;
  upsert?: Prisma.ConferenceRoomUpsertWithoutReservationsInput;
  connect?: Prisma.ConferenceRoomWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.ConferenceRoomUpdateToOneWithWhereWithoutReservationsInput,
      Prisma.ConferenceRoomUpdateWithoutReservationsInput
    >,
    Prisma.ConferenceRoomUncheckedUpdateWithoutReservationsInput
  >;
};

export type ConferenceRoomCreateNestedOneWithoutMaintenanceSchedulesInput = {
  create?: Prisma.XOR<
    Prisma.ConferenceRoomCreateWithoutMaintenanceSchedulesInput,
    Prisma.ConferenceRoomUncheckedCreateWithoutMaintenanceSchedulesInput
  >;
  connectOrCreate?: Prisma.ConferenceRoomCreateOrConnectWithoutMaintenanceSchedulesInput;
  connect?: Prisma.ConferenceRoomWhereUniqueInput;
};

export type ConferenceRoomUpdateOneRequiredWithoutMaintenanceSchedulesNestedInput = {
  create?: Prisma.XOR<
    Prisma.ConferenceRoomCreateWithoutMaintenanceSchedulesInput,
    Prisma.ConferenceRoomUncheckedCreateWithoutMaintenanceSchedulesInput
  >;
  connectOrCreate?: Prisma.ConferenceRoomCreateOrConnectWithoutMaintenanceSchedulesInput;
  upsert?: Prisma.ConferenceRoomUpsertWithoutMaintenanceSchedulesInput;
  connect?: Prisma.ConferenceRoomWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.ConferenceRoomUpdateToOneWithWhereWithoutMaintenanceSchedulesInput,
      Prisma.ConferenceRoomUpdateWithoutMaintenanceSchedulesInput
    >,
    Prisma.ConferenceRoomUncheckedUpdateWithoutMaintenanceSchedulesInput
  >;
};

export type ConferenceRoomCreateWithoutReservationsInput = {
  id?: string;
  name: string;
  capacity: number;
  equipmentList?: Prisma.ConferenceRoomCreateequipmentListInput | string[];
  description?: string | null;
  location?: string | null;
  hourlyRate?: number;
  isActive?: boolean;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  maintenanceSchedules?: Prisma.MaintenanceScheduleCreateNestedManyWithoutRoomInput;
};

export type ConferenceRoomUncheckedCreateWithoutReservationsInput = {
  id?: string;
  name: string;
  capacity: number;
  equipmentList?: Prisma.ConferenceRoomCreateequipmentListInput | string[];
  description?: string | null;
  location?: string | null;
  hourlyRate?: number;
  isActive?: boolean;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  maintenanceSchedules?: Prisma.MaintenanceScheduleUncheckedCreateNestedManyWithoutRoomInput;
};

export type ConferenceRoomCreateOrConnectWithoutReservationsInput = {
  where: Prisma.ConferenceRoomWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.ConferenceRoomCreateWithoutReservationsInput,
    Prisma.ConferenceRoomUncheckedCreateWithoutReservationsInput
  >;
};

export type ConferenceRoomUpsertWithoutReservationsInput = {
  update: Prisma.XOR<
    Prisma.ConferenceRoomUpdateWithoutReservationsInput,
    Prisma.ConferenceRoomUncheckedUpdateWithoutReservationsInput
  >;
  create: Prisma.XOR<
    Prisma.ConferenceRoomCreateWithoutReservationsInput,
    Prisma.ConferenceRoomUncheckedCreateWithoutReservationsInput
  >;
  where?: Prisma.ConferenceRoomWhereInput;
};

export type ConferenceRoomUpdateToOneWithWhereWithoutReservationsInput = {
  where?: Prisma.ConferenceRoomWhereInput;
  data: Prisma.XOR<
    Prisma.ConferenceRoomUpdateWithoutReservationsInput,
    Prisma.ConferenceRoomUncheckedUpdateWithoutReservationsInput
  >;
};

export type ConferenceRoomUpdateWithoutReservationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  capacity?: Prisma.IntFieldUpdateOperationsInput | number;
  equipmentList?: Prisma.ConferenceRoomUpdateequipmentListInput | string[];
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  hourlyRate?: Prisma.FloatFieldUpdateOperationsInput | number;
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  maintenanceSchedules?: Prisma.MaintenanceScheduleUpdateManyWithoutRoomNestedInput;
};

export type ConferenceRoomUncheckedUpdateWithoutReservationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  capacity?: Prisma.IntFieldUpdateOperationsInput | number;
  equipmentList?: Prisma.ConferenceRoomUpdateequipmentListInput | string[];
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  hourlyRate?: Prisma.FloatFieldUpdateOperationsInput | number;
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  maintenanceSchedules?: Prisma.MaintenanceScheduleUncheckedUpdateManyWithoutRoomNestedInput;
};

export type ConferenceRoomCreateWithoutMaintenanceSchedulesInput = {
  id?: string;
  name: string;
  capacity: number;
  equipmentList?: Prisma.ConferenceRoomCreateequipmentListInput | string[];
  description?: string | null;
  location?: string | null;
  hourlyRate?: number;
  isActive?: boolean;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  reservations?: Prisma.ReservationCreateNestedManyWithoutRoomInput;
};

export type ConferenceRoomUncheckedCreateWithoutMaintenanceSchedulesInput = {
  id?: string;
  name: string;
  capacity: number;
  equipmentList?: Prisma.ConferenceRoomCreateequipmentListInput | string[];
  description?: string | null;
  location?: string | null;
  hourlyRate?: number;
  isActive?: boolean;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  reservations?: Prisma.ReservationUncheckedCreateNestedManyWithoutRoomInput;
};

export type ConferenceRoomCreateOrConnectWithoutMaintenanceSchedulesInput = {
  where: Prisma.ConferenceRoomWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.ConferenceRoomCreateWithoutMaintenanceSchedulesInput,
    Prisma.ConferenceRoomUncheckedCreateWithoutMaintenanceSchedulesInput
  >;
};

export type ConferenceRoomUpsertWithoutMaintenanceSchedulesInput = {
  update: Prisma.XOR<
    Prisma.ConferenceRoomUpdateWithoutMaintenanceSchedulesInput,
    Prisma.ConferenceRoomUncheckedUpdateWithoutMaintenanceSchedulesInput
  >;
  create: Prisma.XOR<
    Prisma.ConferenceRoomCreateWithoutMaintenanceSchedulesInput,
    Prisma.ConferenceRoomUncheckedCreateWithoutMaintenanceSchedulesInput
  >;
  where?: Prisma.ConferenceRoomWhereInput;
};

export type ConferenceRoomUpdateToOneWithWhereWithoutMaintenanceSchedulesInput = {
  where?: Prisma.ConferenceRoomWhereInput;
  data: Prisma.XOR<
    Prisma.ConferenceRoomUpdateWithoutMaintenanceSchedulesInput,
    Prisma.ConferenceRoomUncheckedUpdateWithoutMaintenanceSchedulesInput
  >;
};

export type ConferenceRoomUpdateWithoutMaintenanceSchedulesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  capacity?: Prisma.IntFieldUpdateOperationsInput | number;
  equipmentList?: Prisma.ConferenceRoomUpdateequipmentListInput | string[];
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  hourlyRate?: Prisma.FloatFieldUpdateOperationsInput | number;
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  reservations?: Prisma.ReservationUpdateManyWithoutRoomNestedInput;
};

export type ConferenceRoomUncheckedUpdateWithoutMaintenanceSchedulesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  capacity?: Prisma.IntFieldUpdateOperationsInput | number;
  equipmentList?: Prisma.ConferenceRoomUpdateequipmentListInput | string[];
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  hourlyRate?: Prisma.FloatFieldUpdateOperationsInput | number;
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  reservations?: Prisma.ReservationUncheckedUpdateManyWithoutRoomNestedInput;
};

/**
 * Count Type ConferenceRoomCountOutputType
 */

export type ConferenceRoomCountOutputType = {
  reservations: number;
  maintenanceSchedules: number;
};

export type ConferenceRoomCountOutputTypeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  reservations?: boolean | ConferenceRoomCountOutputTypeCountReservationsArgs;
  maintenanceSchedules?: boolean | ConferenceRoomCountOutputTypeCountMaintenanceSchedulesArgs;
};

/**
 * ConferenceRoomCountOutputType without action
 */
export type ConferenceRoomCountOutputTypeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConferenceRoomCountOutputType
   */
  select?: Prisma.ConferenceRoomCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * ConferenceRoomCountOutputType without action
 */
export type ConferenceRoomCountOutputTypeCountReservationsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.ReservationWhereInput;
};

/**
 * ConferenceRoomCountOutputType without action
 */
export type ConferenceRoomCountOutputTypeCountMaintenanceSchedulesArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.MaintenanceScheduleWhereInput;
};

export type ConferenceRoomSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    name?: boolean;
    capacity?: boolean;
    equipmentList?: boolean;
    description?: boolean;
    location?: boolean;
    hourlyRate?: boolean;
    isActive?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    reservations?: boolean | Prisma.ConferenceRoom$reservationsArgs<ExtArgs>;
    maintenanceSchedules?: boolean | Prisma.ConferenceRoom$maintenanceSchedulesArgs<ExtArgs>;
    _count?: boolean | Prisma.ConferenceRoomCountOutputTypeDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['conferenceRoom']
>;

export type ConferenceRoomSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    name?: boolean;
    capacity?: boolean;
    equipmentList?: boolean;
    description?: boolean;
    location?: boolean;
    hourlyRate?: boolean;
    isActive?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
  },
  ExtArgs['result']['conferenceRoom']
>;

export type ConferenceRoomSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    name?: boolean;
    capacity?: boolean;
    equipmentList?: boolean;
    description?: boolean;
    location?: boolean;
    hourlyRate?: boolean;
    isActive?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
  },
  ExtArgs['result']['conferenceRoom']
>;

export type ConferenceRoomSelectScalar = {
  id?: boolean;
  name?: boolean;
  capacity?: boolean;
  equipmentList?: boolean;
  description?: boolean;
  location?: boolean;
  hourlyRate?: boolean;
  isActive?: boolean;
  createdAt?: boolean;
  updatedAt?: boolean;
};

export type ConferenceRoomOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'name'
  | 'capacity'
  | 'equipmentList'
  | 'description'
  | 'location'
  | 'hourlyRate'
  | 'isActive'
  | 'createdAt'
  | 'updatedAt',
  ExtArgs['result']['conferenceRoom']
>;
export type ConferenceRoomInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  reservations?: boolean | Prisma.ConferenceRoom$reservationsArgs<ExtArgs>;
  maintenanceSchedules?: boolean | Prisma.ConferenceRoom$maintenanceSchedulesArgs<ExtArgs>;
  _count?: boolean | Prisma.ConferenceRoomCountOutputTypeDefaultArgs<ExtArgs>;
};
export type ConferenceRoomIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {};
export type ConferenceRoomIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {};

export type $ConferenceRoomPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'ConferenceRoom';
  objects: {
    reservations: Prisma.$ReservationPayload<ExtArgs>[];
    maintenanceSchedules: Prisma.$MaintenanceSchedulePayload<ExtArgs>[];
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      name: string;
      capacity: number;
      equipmentList: string[];
      description: string | null;
      location: string | null;
      hourlyRate: number;
      isActive: boolean;
      createdAt: Date;
      updatedAt: Date;
    },
    ExtArgs['result']['conferenceRoom']
  >;
  composites: {};
};

export type ConferenceRoomGetPayload<
  S extends boolean | null | undefined | ConferenceRoomDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$ConferenceRoomPayload, S>;

export type ConferenceRoomCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<ConferenceRoomFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: ConferenceRoomCountAggregateInputType | true;
};

export interface ConferenceRoomDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['ConferenceRoom'];
    meta: { name: 'ConferenceRoom' };
  };
  /**
   * Find zero or one ConferenceRoom that matches the filter.
   * @param {ConferenceRoomFindUniqueArgs} args - Arguments to find a ConferenceRoom
   * @example
   * // Get one ConferenceRoom
   * const conferenceRoom = await prisma.conferenceRoom.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ConferenceRoomFindUniqueArgs>(
    args: Prisma.SelectSubset<T, ConferenceRoomFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__ConferenceRoomClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConferenceRoomPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one ConferenceRoom that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ConferenceRoomFindUniqueOrThrowArgs} args - Arguments to find a ConferenceRoom
   * @example
   * // Get one ConferenceRoom
   * const conferenceRoom = await prisma.conferenceRoom.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ConferenceRoomFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, ConferenceRoomFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__ConferenceRoomClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConferenceRoomPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ConferenceRoom that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConferenceRoomFindFirstArgs} args - Arguments to find a ConferenceRoom
   * @example
   * // Get one ConferenceRoom
   * const conferenceRoom = await prisma.conferenceRoom.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ConferenceRoomFindFirstArgs>(
    args?: Prisma.SelectSubset<T, ConferenceRoomFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__ConferenceRoomClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConferenceRoomPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ConferenceRoom that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConferenceRoomFindFirstOrThrowArgs} args - Arguments to find a ConferenceRoom
   * @example
   * // Get one ConferenceRoom
   * const conferenceRoom = await prisma.conferenceRoom.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ConferenceRoomFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, ConferenceRoomFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__ConferenceRoomClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConferenceRoomPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more ConferenceRooms that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConferenceRoomFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ConferenceRooms
   * const conferenceRooms = await prisma.conferenceRoom.findMany()
   *
   * // Get first 10 ConferenceRooms
   * const conferenceRooms = await prisma.conferenceRoom.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const conferenceRoomWithIdOnly = await prisma.conferenceRoom.findMany({ select: { id: true } })
   *
   */
  findMany<T extends ConferenceRoomFindManyArgs>(
    args?: Prisma.SelectSubset<T, ConferenceRoomFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ConferenceRoomPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >;

  /**
   * Create a ConferenceRoom.
   * @param {ConferenceRoomCreateArgs} args - Arguments to create a ConferenceRoom.
   * @example
   * // Create one ConferenceRoom
   * const ConferenceRoom = await prisma.conferenceRoom.create({
   *   data: {
   *     // ... data to create a ConferenceRoom
   *   }
   * })
   *
   */
  create<T extends ConferenceRoomCreateArgs>(
    args: Prisma.SelectSubset<T, ConferenceRoomCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__ConferenceRoomClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConferenceRoomPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many ConferenceRooms.
   * @param {ConferenceRoomCreateManyArgs} args - Arguments to create many ConferenceRooms.
   * @example
   * // Create many ConferenceRooms
   * const conferenceRoom = await prisma.conferenceRoom.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends ConferenceRoomCreateManyArgs>(
    args?: Prisma.SelectSubset<T, ConferenceRoomCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many ConferenceRooms and returns the data saved in the database.
   * @param {ConferenceRoomCreateManyAndReturnArgs} args - Arguments to create many ConferenceRooms.
   * @example
   * // Create many ConferenceRooms
   * const conferenceRoom = await prisma.conferenceRoom.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many ConferenceRooms and only return the `id`
   * const conferenceRoomWithIdOnly = await prisma.conferenceRoom.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends ConferenceRoomCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, ConferenceRoomCreateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ConferenceRoomPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a ConferenceRoom.
   * @param {ConferenceRoomDeleteArgs} args - Arguments to delete one ConferenceRoom.
   * @example
   * // Delete one ConferenceRoom
   * const ConferenceRoom = await prisma.conferenceRoom.delete({
   *   where: {
   *     // ... filter to delete one ConferenceRoom
   *   }
   * })
   *
   */
  delete<T extends ConferenceRoomDeleteArgs>(
    args: Prisma.SelectSubset<T, ConferenceRoomDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__ConferenceRoomClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConferenceRoomPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one ConferenceRoom.
   * @param {ConferenceRoomUpdateArgs} args - Arguments to update one ConferenceRoom.
   * @example
   * // Update one ConferenceRoom
   * const conferenceRoom = await prisma.conferenceRoom.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends ConferenceRoomUpdateArgs>(
    args: Prisma.SelectSubset<T, ConferenceRoomUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__ConferenceRoomClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConferenceRoomPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more ConferenceRooms.
   * @param {ConferenceRoomDeleteManyArgs} args - Arguments to filter ConferenceRooms to delete.
   * @example
   * // Delete a few ConferenceRooms
   * const { count } = await prisma.conferenceRoom.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends ConferenceRoomDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, ConferenceRoomDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ConferenceRooms.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConferenceRoomUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ConferenceRooms
   * const conferenceRoom = await prisma.conferenceRoom.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends ConferenceRoomUpdateManyArgs>(
    args: Prisma.SelectSubset<T, ConferenceRoomUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ConferenceRooms and returns the data updated in the database.
   * @param {ConferenceRoomUpdateManyAndReturnArgs} args - Arguments to update many ConferenceRooms.
   * @example
   * // Update many ConferenceRooms
   * const conferenceRoom = await prisma.conferenceRoom.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more ConferenceRooms and only return the `id`
   * const conferenceRoomWithIdOnly = await prisma.conferenceRoom.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends ConferenceRoomUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, ConferenceRoomUpdateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ConferenceRoomPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one ConferenceRoom.
   * @param {ConferenceRoomUpsertArgs} args - Arguments to update or create a ConferenceRoom.
   * @example
   * // Update or create a ConferenceRoom
   * const conferenceRoom = await prisma.conferenceRoom.upsert({
   *   create: {
   *     // ... data to create a ConferenceRoom
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ConferenceRoom we want to update
   *   }
   * })
   */
  upsert<T extends ConferenceRoomUpsertArgs>(
    args: Prisma.SelectSubset<T, ConferenceRoomUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__ConferenceRoomClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConferenceRoomPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of ConferenceRooms.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConferenceRoomCountArgs} args - Arguments to filter ConferenceRooms to count.
   * @example
   * // Count the number of ConferenceRooms
   * const count = await prisma.conferenceRoom.count({
   *   where: {
   *     // ... the filter for the ConferenceRooms we want to count
   *   }
   * })
   **/
  count<T extends ConferenceRoomCountArgs>(
    args?: Prisma.Subset<T, ConferenceRoomCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ConferenceRoomCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a ConferenceRoom.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConferenceRoomAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends ConferenceRoomAggregateArgs>(
    args: Prisma.Subset<T, ConferenceRoomAggregateArgs>,
  ): Prisma.PrismaPromise<GetConferenceRoomAggregateType<T>>;

  /**
   * Group by ConferenceRoom.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConferenceRoomGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends ConferenceRoomGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends (Prisma.True extends HasSelectOrTake
      ? { orderBy: ConferenceRoomGroupByArgs['orderBy'] }
      : { orderBy?: ConferenceRoomGroupByArgs['orderBy'] }),
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends (T['by'] extends never[] ? Prisma.True : Prisma.False),
    InputErrors extends (ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]),
  >(
    args: Prisma.SubsetIntersection<T, ConferenceRoomGroupByArgs, OrderByArg> & InputErrors,
  ): {} extends InputErrors
    ? GetConferenceRoomGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the ConferenceRoom model
   */
  readonly fields: ConferenceRoomFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ConferenceRoom.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ConferenceRoomClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  reservations<T extends Prisma.ConferenceRoom$reservationsArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.ConferenceRoom$reservationsArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$ReservationPayload<ExtArgs>,
        T,
        'findMany',
        GlobalOmitOptions
      >
    | Null
  >;
  maintenanceSchedules<T extends Prisma.ConferenceRoom$maintenanceSchedulesArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.ConferenceRoom$maintenanceSchedulesArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$MaintenanceSchedulePayload<ExtArgs>,
        T,
        'findMany',
        GlobalOmitOptions
      >
    | Null
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the ConferenceRoom model
 */
export interface ConferenceRoomFieldRefs {
  readonly id: Prisma.FieldRef<'ConferenceRoom', 'String'>;
  readonly name: Prisma.FieldRef<'ConferenceRoom', 'String'>;
  readonly capacity: Prisma.FieldRef<'ConferenceRoom', 'Int'>;
  readonly equipmentList: Prisma.FieldRef<'ConferenceRoom', 'String[]'>;
  readonly description: Prisma.FieldRef<'ConferenceRoom', 'String'>;
  readonly location: Prisma.FieldRef<'ConferenceRoom', 'String'>;
  readonly hourlyRate: Prisma.FieldRef<'ConferenceRoom', 'Float'>;
  readonly isActive: Prisma.FieldRef<'ConferenceRoom', 'Boolean'>;
  readonly createdAt: Prisma.FieldRef<'ConferenceRoom', 'DateTime'>;
  readonly updatedAt: Prisma.FieldRef<'ConferenceRoom', 'DateTime'>;
}

// Custom InputTypes
/**
 * ConferenceRoom findUnique
 */
export type ConferenceRoomFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConferenceRoom
   */
  select?: Prisma.ConferenceRoomSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConferenceRoom
   */
  omit?: Prisma.ConferenceRoomOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConferenceRoomInclude<ExtArgs> | null;
  /**
   * Filter, which ConferenceRoom to fetch.
   */
  where: Prisma.ConferenceRoomWhereUniqueInput;
};

/**
 * ConferenceRoom findUniqueOrThrow
 */
export type ConferenceRoomFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConferenceRoom
   */
  select?: Prisma.ConferenceRoomSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConferenceRoom
   */
  omit?: Prisma.ConferenceRoomOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConferenceRoomInclude<ExtArgs> | null;
  /**
   * Filter, which ConferenceRoom to fetch.
   */
  where: Prisma.ConferenceRoomWhereUniqueInput;
};

/**
 * ConferenceRoom findFirst
 */
export type ConferenceRoomFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConferenceRoom
   */
  select?: Prisma.ConferenceRoomSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConferenceRoom
   */
  omit?: Prisma.ConferenceRoomOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConferenceRoomInclude<ExtArgs> | null;
  /**
   * Filter, which ConferenceRoom to fetch.
   */
  where?: Prisma.ConferenceRoomWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ConferenceRooms to fetch.
   */
  orderBy?:
    Prisma.ConferenceRoomOrderByWithRelationInput | Prisma.ConferenceRoomOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ConferenceRooms.
   */
  cursor?: Prisma.ConferenceRoomWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ConferenceRooms from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ConferenceRooms.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ConferenceRooms.
   */
  distinct?: Prisma.ConferenceRoomScalarFieldEnum | Prisma.ConferenceRoomScalarFieldEnum[];
};

/**
 * ConferenceRoom findFirstOrThrow
 */
export type ConferenceRoomFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConferenceRoom
   */
  select?: Prisma.ConferenceRoomSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConferenceRoom
   */
  omit?: Prisma.ConferenceRoomOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConferenceRoomInclude<ExtArgs> | null;
  /**
   * Filter, which ConferenceRoom to fetch.
   */
  where?: Prisma.ConferenceRoomWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ConferenceRooms to fetch.
   */
  orderBy?:
    Prisma.ConferenceRoomOrderByWithRelationInput | Prisma.ConferenceRoomOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ConferenceRooms.
   */
  cursor?: Prisma.ConferenceRoomWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ConferenceRooms from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ConferenceRooms.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ConferenceRooms.
   */
  distinct?: Prisma.ConferenceRoomScalarFieldEnum | Prisma.ConferenceRoomScalarFieldEnum[];
};

/**
 * ConferenceRoom findMany
 */
export type ConferenceRoomFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConferenceRoom
   */
  select?: Prisma.ConferenceRoomSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConferenceRoom
   */
  omit?: Prisma.ConferenceRoomOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConferenceRoomInclude<ExtArgs> | null;
  /**
   * Filter, which ConferenceRooms to fetch.
   */
  where?: Prisma.ConferenceRoomWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ConferenceRooms to fetch.
   */
  orderBy?:
    Prisma.ConferenceRoomOrderByWithRelationInput | Prisma.ConferenceRoomOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing ConferenceRooms.
   */
  cursor?: Prisma.ConferenceRoomWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ConferenceRooms from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ConferenceRooms.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ConferenceRooms.
   */
  distinct?: Prisma.ConferenceRoomScalarFieldEnum | Prisma.ConferenceRoomScalarFieldEnum[];
};

/**
 * ConferenceRoom create
 */
export type ConferenceRoomCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConferenceRoom
   */
  select?: Prisma.ConferenceRoomSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConferenceRoom
   */
  omit?: Prisma.ConferenceRoomOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConferenceRoomInclude<ExtArgs> | null;
  /**
   * The data needed to create a ConferenceRoom.
   */
  data: Prisma.XOR<Prisma.ConferenceRoomCreateInput, Prisma.ConferenceRoomUncheckedCreateInput>;
};

/**
 * ConferenceRoom createMany
 */
export type ConferenceRoomCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many ConferenceRooms.
   */
  data: Prisma.ConferenceRoomCreateManyInput | Prisma.ConferenceRoomCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * ConferenceRoom createManyAndReturn
 */
export type ConferenceRoomCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConferenceRoom
   */
  select?: Prisma.ConferenceRoomSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the ConferenceRoom
   */
  omit?: Prisma.ConferenceRoomOmit<ExtArgs> | null;
  /**
   * The data used to create many ConferenceRooms.
   */
  data: Prisma.ConferenceRoomCreateManyInput | Prisma.ConferenceRoomCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * ConferenceRoom update
 */
export type ConferenceRoomUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConferenceRoom
   */
  select?: Prisma.ConferenceRoomSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConferenceRoom
   */
  omit?: Prisma.ConferenceRoomOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConferenceRoomInclude<ExtArgs> | null;
  /**
   * The data needed to update a ConferenceRoom.
   */
  data: Prisma.XOR<Prisma.ConferenceRoomUpdateInput, Prisma.ConferenceRoomUncheckedUpdateInput>;
  /**
   * Choose, which ConferenceRoom to update.
   */
  where: Prisma.ConferenceRoomWhereUniqueInput;
};

/**
 * ConferenceRoom updateMany
 */
export type ConferenceRoomUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update ConferenceRooms.
   */
  data: Prisma.XOR<
    Prisma.ConferenceRoomUpdateManyMutationInput,
    Prisma.ConferenceRoomUncheckedUpdateManyInput
  >;
  /**
   * Filter which ConferenceRooms to update
   */
  where?: Prisma.ConferenceRoomWhereInput;
  /**
   * Limit how many ConferenceRooms to update.
   */
  limit?: number;
};

/**
 * ConferenceRoom updateManyAndReturn
 */
export type ConferenceRoomUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConferenceRoom
   */
  select?: Prisma.ConferenceRoomSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the ConferenceRoom
   */
  omit?: Prisma.ConferenceRoomOmit<ExtArgs> | null;
  /**
   * The data used to update ConferenceRooms.
   */
  data: Prisma.XOR<
    Prisma.ConferenceRoomUpdateManyMutationInput,
    Prisma.ConferenceRoomUncheckedUpdateManyInput
  >;
  /**
   * Filter which ConferenceRooms to update
   */
  where?: Prisma.ConferenceRoomWhereInput;
  /**
   * Limit how many ConferenceRooms to update.
   */
  limit?: number;
};

/**
 * ConferenceRoom upsert
 */
export type ConferenceRoomUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConferenceRoom
   */
  select?: Prisma.ConferenceRoomSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConferenceRoom
   */
  omit?: Prisma.ConferenceRoomOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConferenceRoomInclude<ExtArgs> | null;
  /**
   * The filter to search for the ConferenceRoom to update in case it exists.
   */
  where: Prisma.ConferenceRoomWhereUniqueInput;
  /**
   * In case the ConferenceRoom found by the `where` argument doesn't exist, create a new ConferenceRoom with this data.
   */
  create: Prisma.XOR<Prisma.ConferenceRoomCreateInput, Prisma.ConferenceRoomUncheckedCreateInput>;
  /**
   * In case the ConferenceRoom was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ConferenceRoomUpdateInput, Prisma.ConferenceRoomUncheckedUpdateInput>;
};

/**
 * ConferenceRoom delete
 */
export type ConferenceRoomDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConferenceRoom
   */
  select?: Prisma.ConferenceRoomSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConferenceRoom
   */
  omit?: Prisma.ConferenceRoomOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConferenceRoomInclude<ExtArgs> | null;
  /**
   * Filter which ConferenceRoom to delete.
   */
  where: Prisma.ConferenceRoomWhereUniqueInput;
};

/**
 * ConferenceRoom deleteMany
 */
export type ConferenceRoomDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ConferenceRooms to delete
   */
  where?: Prisma.ConferenceRoomWhereInput;
  /**
   * Limit how many ConferenceRooms to delete.
   */
  limit?: number;
};

/**
 * ConferenceRoom.reservations
 */
export type ConferenceRoom$reservationsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Reservation
   */
  select?: Prisma.ReservationSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Reservation
   */
  omit?: Prisma.ReservationOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReservationInclude<ExtArgs> | null;
  where?: Prisma.ReservationWhereInput;
  orderBy?:
    Prisma.ReservationOrderByWithRelationInput | Prisma.ReservationOrderByWithRelationInput[];
  cursor?: Prisma.ReservationWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?: Prisma.ReservationScalarFieldEnum | Prisma.ReservationScalarFieldEnum[];
};

/**
 * ConferenceRoom.maintenanceSchedules
 */
export type ConferenceRoom$maintenanceSchedulesArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the MaintenanceSchedule
   */
  select?: Prisma.MaintenanceScheduleSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the MaintenanceSchedule
   */
  omit?: Prisma.MaintenanceScheduleOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceScheduleInclude<ExtArgs> | null;
  where?: Prisma.MaintenanceScheduleWhereInput;
  orderBy?:
    | Prisma.MaintenanceScheduleOrderByWithRelationInput
    | Prisma.MaintenanceScheduleOrderByWithRelationInput[];
  cursor?: Prisma.MaintenanceScheduleWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?:
    Prisma.MaintenanceScheduleScalarFieldEnum | Prisma.MaintenanceScheduleScalarFieldEnum[];
};

/**
 * ConferenceRoom without action
 */
export type ConferenceRoomDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConferenceRoom
   */
  select?: Prisma.ConferenceRoomSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConferenceRoom
   */
  omit?: Prisma.ConferenceRoomOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConferenceRoomInclude<ExtArgs> | null;
};
