/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `UsageLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.js';
import type * as Prisma from '../internal/prismaNamespace.js';

/**
 * Model UsageLog
 *
 */
export type UsageLogModel = runtime.Types.Result.DefaultSelection<Prisma.$UsageLogPayload>;

export type AggregateUsageLog = {
  _count: UsageLogCountAggregateOutputType | null;
  _avg: UsageLogAvgAggregateOutputType | null;
  _sum: UsageLogSumAggregateOutputType | null;
  _min: UsageLogMinAggregateOutputType | null;
  _max: UsageLogMaxAggregateOutputType | null;
};

export type UsageLogAvgAggregateOutputType = {
  scheduledMinutes: number | null;
  actualConsumedMinutes: number | null;
  billableMins: number | null;
  overstayMinutes: number | null;
  billingAmount: number | null;
};

export type UsageLogSumAggregateOutputType = {
  scheduledMinutes: number | null;
  actualConsumedMinutes: number | null;
  billableMins: number | null;
  overstayMinutes: number | null;
  billingAmount: number | null;
};

export type UsageLogMinAggregateOutputType = {
  id: string | null;
  reservationId: string | null;
  clientId: string | null;
  userId: string | null;
  roomId: string | null;
  scheduledStart: Date | null;
  scheduledEnd: Date | null;
  startTime: Date | null;
  endTime: Date | null;
  scheduledMinutes: number | null;
  actualConsumedMinutes: number | null;
  billableMins: number | null;
  overstayMinutes: number | null;
  billingAmount: number | null;
  overstayed: boolean | null;
  createdAt: Date | null;
};

export type UsageLogMaxAggregateOutputType = {
  id: string | null;
  reservationId: string | null;
  clientId: string | null;
  userId: string | null;
  roomId: string | null;
  scheduledStart: Date | null;
  scheduledEnd: Date | null;
  startTime: Date | null;
  endTime: Date | null;
  scheduledMinutes: number | null;
  actualConsumedMinutes: number | null;
  billableMins: number | null;
  overstayMinutes: number | null;
  billingAmount: number | null;
  overstayed: boolean | null;
  createdAt: Date | null;
};

export type UsageLogCountAggregateOutputType = {
  id: number;
  reservationId: number;
  clientId: number;
  userId: number;
  roomId: number;
  scheduledStart: number;
  scheduledEnd: number;
  startTime: number;
  endTime: number;
  scheduledMinutes: number;
  actualConsumedMinutes: number;
  billableMins: number;
  overstayMinutes: number;
  billingAmount: number;
  overstayed: number;
  createdAt: number;
  _all: number;
};

export type UsageLogAvgAggregateInputType = {
  scheduledMinutes?: true;
  actualConsumedMinutes?: true;
  billableMins?: true;
  overstayMinutes?: true;
  billingAmount?: true;
};

export type UsageLogSumAggregateInputType = {
  scheduledMinutes?: true;
  actualConsumedMinutes?: true;
  billableMins?: true;
  overstayMinutes?: true;
  billingAmount?: true;
};

export type UsageLogMinAggregateInputType = {
  id?: true;
  reservationId?: true;
  clientId?: true;
  userId?: true;
  roomId?: true;
  scheduledStart?: true;
  scheduledEnd?: true;
  startTime?: true;
  endTime?: true;
  scheduledMinutes?: true;
  actualConsumedMinutes?: true;
  billableMins?: true;
  overstayMinutes?: true;
  billingAmount?: true;
  overstayed?: true;
  createdAt?: true;
};

export type UsageLogMaxAggregateInputType = {
  id?: true;
  reservationId?: true;
  clientId?: true;
  userId?: true;
  roomId?: true;
  scheduledStart?: true;
  scheduledEnd?: true;
  startTime?: true;
  endTime?: true;
  scheduledMinutes?: true;
  actualConsumedMinutes?: true;
  billableMins?: true;
  overstayMinutes?: true;
  billingAmount?: true;
  overstayed?: true;
  createdAt?: true;
};

export type UsageLogCountAggregateInputType = {
  id?: true;
  reservationId?: true;
  clientId?: true;
  userId?: true;
  roomId?: true;
  scheduledStart?: true;
  scheduledEnd?: true;
  startTime?: true;
  endTime?: true;
  scheduledMinutes?: true;
  actualConsumedMinutes?: true;
  billableMins?: true;
  overstayMinutes?: true;
  billingAmount?: true;
  overstayed?: true;
  createdAt?: true;
  _all?: true;
};

export type UsageLogAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which UsageLog to aggregate.
   */
  where?: Prisma.UsageLogWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UsageLogs to fetch.
   */
  orderBy?: Prisma.UsageLogOrderByWithRelationInput | Prisma.UsageLogOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.UsageLogWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UsageLogs from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UsageLogs.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned UsageLogs
   **/
  _count?: true | UsageLogCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: UsageLogAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: UsageLogSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: UsageLogMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: UsageLogMaxAggregateInputType;
};

export type GetUsageLogAggregateType<T extends UsageLogAggregateArgs> = {
  [P in keyof T & keyof AggregateUsageLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUsageLog[P]>
    : Prisma.GetScalarType<T[P], AggregateUsageLog[P]>;
};

export type UsageLogGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.UsageLogWhereInput;
  orderBy?:
    Prisma.UsageLogOrderByWithAggregationInput | Prisma.UsageLogOrderByWithAggregationInput[];
  by: Prisma.UsageLogScalarFieldEnum[] | Prisma.UsageLogScalarFieldEnum;
  having?: Prisma.UsageLogScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: UsageLogCountAggregateInputType | true;
  _avg?: UsageLogAvgAggregateInputType;
  _sum?: UsageLogSumAggregateInputType;
  _min?: UsageLogMinAggregateInputType;
  _max?: UsageLogMaxAggregateInputType;
};

export type UsageLogGroupByOutputType = {
  id: string;
  reservationId: string;
  clientId: string;
  userId: string;
  roomId: string;
  scheduledStart: Date;
  scheduledEnd: Date;
  startTime: Date;
  endTime: Date | null;
  scheduledMinutes: number;
  actualConsumedMinutes: number;
  billableMins: number;
  overstayMinutes: number;
  billingAmount: number;
  overstayed: boolean;
  createdAt: Date;
  _count: UsageLogCountAggregateOutputType | null;
  _avg: UsageLogAvgAggregateOutputType | null;
  _sum: UsageLogSumAggregateOutputType | null;
  _min: UsageLogMinAggregateOutputType | null;
  _max: UsageLogMaxAggregateOutputType | null;
};

export type GetUsageLogGroupByPayload<T extends UsageLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UsageLogGroupByOutputType, T['by']> & {
      [P in keyof T & keyof UsageLogGroupByOutputType]: P extends '_count'
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], UsageLogGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], UsageLogGroupByOutputType[P]>;
    }
  >
>;

export type UsageLogWhereInput = {
  AND?: Prisma.UsageLogWhereInput | Prisma.UsageLogWhereInput[];
  OR?: Prisma.UsageLogWhereInput[];
  NOT?: Prisma.UsageLogWhereInput | Prisma.UsageLogWhereInput[];
  id?: Prisma.StringFilter<'UsageLog'> | string;
  reservationId?: Prisma.StringFilter<'UsageLog'> | string;
  clientId?: Prisma.StringFilter<'UsageLog'> | string;
  userId?: Prisma.StringFilter<'UsageLog'> | string;
  roomId?: Prisma.StringFilter<'UsageLog'> | string;
  scheduledStart?: Prisma.DateTimeFilter<'UsageLog'> | Date | string;
  scheduledEnd?: Prisma.DateTimeFilter<'UsageLog'> | Date | string;
  startTime?: Prisma.DateTimeFilter<'UsageLog'> | Date | string;
  endTime?: Prisma.DateTimeNullableFilter<'UsageLog'> | Date | string | null;
  scheduledMinutes?: Prisma.IntFilter<'UsageLog'> | number;
  actualConsumedMinutes?: Prisma.IntFilter<'UsageLog'> | number;
  billableMins?: Prisma.IntFilter<'UsageLog'> | number;
  overstayMinutes?: Prisma.IntFilter<'UsageLog'> | number;
  billingAmount?: Prisma.FloatFilter<'UsageLog'> | number;
  overstayed?: Prisma.BoolFilter<'UsageLog'> | boolean;
  createdAt?: Prisma.DateTimeFilter<'UsageLog'> | Date | string;
  reservation?: Prisma.XOR<Prisma.ReservationScalarRelationFilter, Prisma.ReservationWhereInput>;
  client?: Prisma.XOR<Prisma.ClientCompanyScalarRelationFilter, Prisma.ClientCompanyWhereInput>;
};

export type UsageLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  reservationId?: Prisma.SortOrder;
  clientId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  roomId?: Prisma.SortOrder;
  scheduledStart?: Prisma.SortOrder;
  scheduledEnd?: Prisma.SortOrder;
  startTime?: Prisma.SortOrder;
  endTime?: Prisma.SortOrderInput | Prisma.SortOrder;
  scheduledMinutes?: Prisma.SortOrder;
  actualConsumedMinutes?: Prisma.SortOrder;
  billableMins?: Prisma.SortOrder;
  overstayMinutes?: Prisma.SortOrder;
  billingAmount?: Prisma.SortOrder;
  overstayed?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  reservation?: Prisma.ReservationOrderByWithRelationInput;
  client?: Prisma.ClientCompanyOrderByWithRelationInput;
};

export type UsageLogWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    reservationId?: string;
    AND?: Prisma.UsageLogWhereInput | Prisma.UsageLogWhereInput[];
    OR?: Prisma.UsageLogWhereInput[];
    NOT?: Prisma.UsageLogWhereInput | Prisma.UsageLogWhereInput[];
    clientId?: Prisma.StringFilter<'UsageLog'> | string;
    userId?: Prisma.StringFilter<'UsageLog'> | string;
    roomId?: Prisma.StringFilter<'UsageLog'> | string;
    scheduledStart?: Prisma.DateTimeFilter<'UsageLog'> | Date | string;
    scheduledEnd?: Prisma.DateTimeFilter<'UsageLog'> | Date | string;
    startTime?: Prisma.DateTimeFilter<'UsageLog'> | Date | string;
    endTime?: Prisma.DateTimeNullableFilter<'UsageLog'> | Date | string | null;
    scheduledMinutes?: Prisma.IntFilter<'UsageLog'> | number;
    actualConsumedMinutes?: Prisma.IntFilter<'UsageLog'> | number;
    billableMins?: Prisma.IntFilter<'UsageLog'> | number;
    overstayMinutes?: Prisma.IntFilter<'UsageLog'> | number;
    billingAmount?: Prisma.FloatFilter<'UsageLog'> | number;
    overstayed?: Prisma.BoolFilter<'UsageLog'> | boolean;
    createdAt?: Prisma.DateTimeFilter<'UsageLog'> | Date | string;
    reservation?: Prisma.XOR<Prisma.ReservationScalarRelationFilter, Prisma.ReservationWhereInput>;
    client?: Prisma.XOR<Prisma.ClientCompanyScalarRelationFilter, Prisma.ClientCompanyWhereInput>;
  },
  'id' | 'reservationId'
>;

export type UsageLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  reservationId?: Prisma.SortOrder;
  clientId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  roomId?: Prisma.SortOrder;
  scheduledStart?: Prisma.SortOrder;
  scheduledEnd?: Prisma.SortOrder;
  startTime?: Prisma.SortOrder;
  endTime?: Prisma.SortOrderInput | Prisma.SortOrder;
  scheduledMinutes?: Prisma.SortOrder;
  actualConsumedMinutes?: Prisma.SortOrder;
  billableMins?: Prisma.SortOrder;
  overstayMinutes?: Prisma.SortOrder;
  billingAmount?: Prisma.SortOrder;
  overstayed?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  _count?: Prisma.UsageLogCountOrderByAggregateInput;
  _avg?: Prisma.UsageLogAvgOrderByAggregateInput;
  _max?: Prisma.UsageLogMaxOrderByAggregateInput;
  _min?: Prisma.UsageLogMinOrderByAggregateInput;
  _sum?: Prisma.UsageLogSumOrderByAggregateInput;
};

export type UsageLogScalarWhereWithAggregatesInput = {
  AND?:
    Prisma.UsageLogScalarWhereWithAggregatesInput | Prisma.UsageLogScalarWhereWithAggregatesInput[];
  OR?: Prisma.UsageLogScalarWhereWithAggregatesInput[];
  NOT?:
    Prisma.UsageLogScalarWhereWithAggregatesInput | Prisma.UsageLogScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<'UsageLog'> | string;
  reservationId?: Prisma.StringWithAggregatesFilter<'UsageLog'> | string;
  clientId?: Prisma.StringWithAggregatesFilter<'UsageLog'> | string;
  userId?: Prisma.StringWithAggregatesFilter<'UsageLog'> | string;
  roomId?: Prisma.StringWithAggregatesFilter<'UsageLog'> | string;
  scheduledStart?: Prisma.DateTimeWithAggregatesFilter<'UsageLog'> | Date | string;
  scheduledEnd?: Prisma.DateTimeWithAggregatesFilter<'UsageLog'> | Date | string;
  startTime?: Prisma.DateTimeWithAggregatesFilter<'UsageLog'> | Date | string;
  endTime?: Prisma.DateTimeNullableWithAggregatesFilter<'UsageLog'> | Date | string | null;
  scheduledMinutes?: Prisma.IntWithAggregatesFilter<'UsageLog'> | number;
  actualConsumedMinutes?: Prisma.IntWithAggregatesFilter<'UsageLog'> | number;
  billableMins?: Prisma.IntWithAggregatesFilter<'UsageLog'> | number;
  overstayMinutes?: Prisma.IntWithAggregatesFilter<'UsageLog'> | number;
  billingAmount?: Prisma.FloatWithAggregatesFilter<'UsageLog'> | number;
  overstayed?: Prisma.BoolWithAggregatesFilter<'UsageLog'> | boolean;
  createdAt?: Prisma.DateTimeWithAggregatesFilter<'UsageLog'> | Date | string;
};

export type UsageLogCreateInput = {
  id?: string;
  userId: string;
  roomId: string;
  scheduledStart: Date | string;
  scheduledEnd: Date | string;
  startTime: Date | string;
  endTime?: Date | string | null;
  scheduledMinutes: number;
  actualConsumedMinutes?: number;
  billableMins?: number;
  overstayMinutes?: number;
  billingAmount?: number;
  overstayed?: boolean;
  createdAt?: Date | string;
  reservation: Prisma.ReservationCreateNestedOneWithoutUsageLogInput;
  client: Prisma.ClientCompanyCreateNestedOneWithoutUsageLogsInput;
};

export type UsageLogUncheckedCreateInput = {
  id?: string;
  reservationId: string;
  clientId: string;
  userId: string;
  roomId: string;
  scheduledStart: Date | string;
  scheduledEnd: Date | string;
  startTime: Date | string;
  endTime?: Date | string | null;
  scheduledMinutes: number;
  actualConsumedMinutes?: number;
  billableMins?: number;
  overstayMinutes?: number;
  billingAmount?: number;
  overstayed?: boolean;
  createdAt?: Date | string;
};

export type UsageLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  roomId?: Prisma.StringFieldUpdateOperationsInput | string;
  scheduledStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  scheduledEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  scheduledMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  actualConsumedMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billableMins?: Prisma.IntFieldUpdateOperationsInput | number;
  overstayMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billingAmount?: Prisma.FloatFieldUpdateOperationsInput | number;
  overstayed?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  reservation?: Prisma.ReservationUpdateOneRequiredWithoutUsageLogNestedInput;
  client?: Prisma.ClientCompanyUpdateOneRequiredWithoutUsageLogsNestedInput;
};

export type UsageLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  reservationId?: Prisma.StringFieldUpdateOperationsInput | string;
  clientId?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  roomId?: Prisma.StringFieldUpdateOperationsInput | string;
  scheduledStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  scheduledEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  scheduledMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  actualConsumedMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billableMins?: Prisma.IntFieldUpdateOperationsInput | number;
  overstayMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billingAmount?: Prisma.FloatFieldUpdateOperationsInput | number;
  overstayed?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type UsageLogCreateManyInput = {
  id?: string;
  reservationId: string;
  clientId: string;
  userId: string;
  roomId: string;
  scheduledStart: Date | string;
  scheduledEnd: Date | string;
  startTime: Date | string;
  endTime?: Date | string | null;
  scheduledMinutes: number;
  actualConsumedMinutes?: number;
  billableMins?: number;
  overstayMinutes?: number;
  billingAmount?: number;
  overstayed?: boolean;
  createdAt?: Date | string;
};

export type UsageLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  roomId?: Prisma.StringFieldUpdateOperationsInput | string;
  scheduledStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  scheduledEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  scheduledMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  actualConsumedMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billableMins?: Prisma.IntFieldUpdateOperationsInput | number;
  overstayMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billingAmount?: Prisma.FloatFieldUpdateOperationsInput | number;
  overstayed?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type UsageLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  reservationId?: Prisma.StringFieldUpdateOperationsInput | string;
  clientId?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  roomId?: Prisma.StringFieldUpdateOperationsInput | string;
  scheduledStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  scheduledEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  scheduledMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  actualConsumedMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billableMins?: Prisma.IntFieldUpdateOperationsInput | number;
  overstayMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billingAmount?: Prisma.FloatFieldUpdateOperationsInput | number;
  overstayed?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type UsageLogListRelationFilter = {
  every?: Prisma.UsageLogWhereInput;
  some?: Prisma.UsageLogWhereInput;
  none?: Prisma.UsageLogWhereInput;
};

export type UsageLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type UsageLogNullableScalarRelationFilter = {
  is?: Prisma.UsageLogWhereInput | null;
  isNot?: Prisma.UsageLogWhereInput | null;
};

export type UsageLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  reservationId?: Prisma.SortOrder;
  clientId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  roomId?: Prisma.SortOrder;
  scheduledStart?: Prisma.SortOrder;
  scheduledEnd?: Prisma.SortOrder;
  startTime?: Prisma.SortOrder;
  endTime?: Prisma.SortOrder;
  scheduledMinutes?: Prisma.SortOrder;
  actualConsumedMinutes?: Prisma.SortOrder;
  billableMins?: Prisma.SortOrder;
  overstayMinutes?: Prisma.SortOrder;
  billingAmount?: Prisma.SortOrder;
  overstayed?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type UsageLogAvgOrderByAggregateInput = {
  scheduledMinutes?: Prisma.SortOrder;
  actualConsumedMinutes?: Prisma.SortOrder;
  billableMins?: Prisma.SortOrder;
  overstayMinutes?: Prisma.SortOrder;
  billingAmount?: Prisma.SortOrder;
};

export type UsageLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  reservationId?: Prisma.SortOrder;
  clientId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  roomId?: Prisma.SortOrder;
  scheduledStart?: Prisma.SortOrder;
  scheduledEnd?: Prisma.SortOrder;
  startTime?: Prisma.SortOrder;
  endTime?: Prisma.SortOrder;
  scheduledMinutes?: Prisma.SortOrder;
  actualConsumedMinutes?: Prisma.SortOrder;
  billableMins?: Prisma.SortOrder;
  overstayMinutes?: Prisma.SortOrder;
  billingAmount?: Prisma.SortOrder;
  overstayed?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type UsageLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  reservationId?: Prisma.SortOrder;
  clientId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  roomId?: Prisma.SortOrder;
  scheduledStart?: Prisma.SortOrder;
  scheduledEnd?: Prisma.SortOrder;
  startTime?: Prisma.SortOrder;
  endTime?: Prisma.SortOrder;
  scheduledMinutes?: Prisma.SortOrder;
  actualConsumedMinutes?: Prisma.SortOrder;
  billableMins?: Prisma.SortOrder;
  overstayMinutes?: Prisma.SortOrder;
  billingAmount?: Prisma.SortOrder;
  overstayed?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type UsageLogSumOrderByAggregateInput = {
  scheduledMinutes?: Prisma.SortOrder;
  actualConsumedMinutes?: Prisma.SortOrder;
  billableMins?: Prisma.SortOrder;
  overstayMinutes?: Prisma.SortOrder;
  billingAmount?: Prisma.SortOrder;
};

export type UsageLogCreateNestedManyWithoutClientInput = {
  create?:
    | Prisma.XOR<
        Prisma.UsageLogCreateWithoutClientInput,
        Prisma.UsageLogUncheckedCreateWithoutClientInput
      >
    | Prisma.UsageLogCreateWithoutClientInput[]
    | Prisma.UsageLogUncheckedCreateWithoutClientInput[];
  connectOrCreate?:
    | Prisma.UsageLogCreateOrConnectWithoutClientInput
    | Prisma.UsageLogCreateOrConnectWithoutClientInput[];
  createMany?: Prisma.UsageLogCreateManyClientInputEnvelope;
  connect?: Prisma.UsageLogWhereUniqueInput | Prisma.UsageLogWhereUniqueInput[];
};

export type UsageLogUncheckedCreateNestedManyWithoutClientInput = {
  create?:
    | Prisma.XOR<
        Prisma.UsageLogCreateWithoutClientInput,
        Prisma.UsageLogUncheckedCreateWithoutClientInput
      >
    | Prisma.UsageLogCreateWithoutClientInput[]
    | Prisma.UsageLogUncheckedCreateWithoutClientInput[];
  connectOrCreate?:
    | Prisma.UsageLogCreateOrConnectWithoutClientInput
    | Prisma.UsageLogCreateOrConnectWithoutClientInput[];
  createMany?: Prisma.UsageLogCreateManyClientInputEnvelope;
  connect?: Prisma.UsageLogWhereUniqueInput | Prisma.UsageLogWhereUniqueInput[];
};

export type UsageLogUpdateManyWithoutClientNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.UsageLogCreateWithoutClientInput,
        Prisma.UsageLogUncheckedCreateWithoutClientInput
      >
    | Prisma.UsageLogCreateWithoutClientInput[]
    | Prisma.UsageLogUncheckedCreateWithoutClientInput[];
  connectOrCreate?:
    | Prisma.UsageLogCreateOrConnectWithoutClientInput
    | Prisma.UsageLogCreateOrConnectWithoutClientInput[];
  upsert?:
    | Prisma.UsageLogUpsertWithWhereUniqueWithoutClientInput
    | Prisma.UsageLogUpsertWithWhereUniqueWithoutClientInput[];
  createMany?: Prisma.UsageLogCreateManyClientInputEnvelope;
  set?: Prisma.UsageLogWhereUniqueInput | Prisma.UsageLogWhereUniqueInput[];
  disconnect?: Prisma.UsageLogWhereUniqueInput | Prisma.UsageLogWhereUniqueInput[];
  delete?: Prisma.UsageLogWhereUniqueInput | Prisma.UsageLogWhereUniqueInput[];
  connect?: Prisma.UsageLogWhereUniqueInput | Prisma.UsageLogWhereUniqueInput[];
  update?:
    | Prisma.UsageLogUpdateWithWhereUniqueWithoutClientInput
    | Prisma.UsageLogUpdateWithWhereUniqueWithoutClientInput[];
  updateMany?:
    | Prisma.UsageLogUpdateManyWithWhereWithoutClientInput
    | Prisma.UsageLogUpdateManyWithWhereWithoutClientInput[];
  deleteMany?: Prisma.UsageLogScalarWhereInput | Prisma.UsageLogScalarWhereInput[];
};

export type UsageLogUncheckedUpdateManyWithoutClientNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.UsageLogCreateWithoutClientInput,
        Prisma.UsageLogUncheckedCreateWithoutClientInput
      >
    | Prisma.UsageLogCreateWithoutClientInput[]
    | Prisma.UsageLogUncheckedCreateWithoutClientInput[];
  connectOrCreate?:
    | Prisma.UsageLogCreateOrConnectWithoutClientInput
    | Prisma.UsageLogCreateOrConnectWithoutClientInput[];
  upsert?:
    | Prisma.UsageLogUpsertWithWhereUniqueWithoutClientInput
    | Prisma.UsageLogUpsertWithWhereUniqueWithoutClientInput[];
  createMany?: Prisma.UsageLogCreateManyClientInputEnvelope;
  set?: Prisma.UsageLogWhereUniqueInput | Prisma.UsageLogWhereUniqueInput[];
  disconnect?: Prisma.UsageLogWhereUniqueInput | Prisma.UsageLogWhereUniqueInput[];
  delete?: Prisma.UsageLogWhereUniqueInput | Prisma.UsageLogWhereUniqueInput[];
  connect?: Prisma.UsageLogWhereUniqueInput | Prisma.UsageLogWhereUniqueInput[];
  update?:
    | Prisma.UsageLogUpdateWithWhereUniqueWithoutClientInput
    | Prisma.UsageLogUpdateWithWhereUniqueWithoutClientInput[];
  updateMany?:
    | Prisma.UsageLogUpdateManyWithWhereWithoutClientInput
    | Prisma.UsageLogUpdateManyWithWhereWithoutClientInput[];
  deleteMany?: Prisma.UsageLogScalarWhereInput | Prisma.UsageLogScalarWhereInput[];
};

export type UsageLogCreateNestedOneWithoutReservationInput = {
  create?: Prisma.XOR<
    Prisma.UsageLogCreateWithoutReservationInput,
    Prisma.UsageLogUncheckedCreateWithoutReservationInput
  >;
  connectOrCreate?: Prisma.UsageLogCreateOrConnectWithoutReservationInput;
  connect?: Prisma.UsageLogWhereUniqueInput;
};

export type UsageLogUncheckedCreateNestedOneWithoutReservationInput = {
  create?: Prisma.XOR<
    Prisma.UsageLogCreateWithoutReservationInput,
    Prisma.UsageLogUncheckedCreateWithoutReservationInput
  >;
  connectOrCreate?: Prisma.UsageLogCreateOrConnectWithoutReservationInput;
  connect?: Prisma.UsageLogWhereUniqueInput;
};

export type UsageLogUpdateOneWithoutReservationNestedInput = {
  create?: Prisma.XOR<
    Prisma.UsageLogCreateWithoutReservationInput,
    Prisma.UsageLogUncheckedCreateWithoutReservationInput
  >;
  connectOrCreate?: Prisma.UsageLogCreateOrConnectWithoutReservationInput;
  upsert?: Prisma.UsageLogUpsertWithoutReservationInput;
  disconnect?: Prisma.UsageLogWhereInput | boolean;
  delete?: Prisma.UsageLogWhereInput | boolean;
  connect?: Prisma.UsageLogWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.UsageLogUpdateToOneWithWhereWithoutReservationInput,
      Prisma.UsageLogUpdateWithoutReservationInput
    >,
    Prisma.UsageLogUncheckedUpdateWithoutReservationInput
  >;
};

export type UsageLogUncheckedUpdateOneWithoutReservationNestedInput = {
  create?: Prisma.XOR<
    Prisma.UsageLogCreateWithoutReservationInput,
    Prisma.UsageLogUncheckedCreateWithoutReservationInput
  >;
  connectOrCreate?: Prisma.UsageLogCreateOrConnectWithoutReservationInput;
  upsert?: Prisma.UsageLogUpsertWithoutReservationInput;
  disconnect?: Prisma.UsageLogWhereInput | boolean;
  delete?: Prisma.UsageLogWhereInput | boolean;
  connect?: Prisma.UsageLogWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.UsageLogUpdateToOneWithWhereWithoutReservationInput,
      Prisma.UsageLogUpdateWithoutReservationInput
    >,
    Prisma.UsageLogUncheckedUpdateWithoutReservationInput
  >;
};

export type UsageLogCreateWithoutClientInput = {
  id?: string;
  userId: string;
  roomId: string;
  scheduledStart: Date | string;
  scheduledEnd: Date | string;
  startTime: Date | string;
  endTime?: Date | string | null;
  scheduledMinutes: number;
  actualConsumedMinutes?: number;
  billableMins?: number;
  overstayMinutes?: number;
  billingAmount?: number;
  overstayed?: boolean;
  createdAt?: Date | string;
  reservation: Prisma.ReservationCreateNestedOneWithoutUsageLogInput;
};

export type UsageLogUncheckedCreateWithoutClientInput = {
  id?: string;
  reservationId: string;
  userId: string;
  roomId: string;
  scheduledStart: Date | string;
  scheduledEnd: Date | string;
  startTime: Date | string;
  endTime?: Date | string | null;
  scheduledMinutes: number;
  actualConsumedMinutes?: number;
  billableMins?: number;
  overstayMinutes?: number;
  billingAmount?: number;
  overstayed?: boolean;
  createdAt?: Date | string;
};

export type UsageLogCreateOrConnectWithoutClientInput = {
  where: Prisma.UsageLogWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.UsageLogCreateWithoutClientInput,
    Prisma.UsageLogUncheckedCreateWithoutClientInput
  >;
};

export type UsageLogCreateManyClientInputEnvelope = {
  data: Prisma.UsageLogCreateManyClientInput | Prisma.UsageLogCreateManyClientInput[];
  skipDuplicates?: boolean;
};

export type UsageLogUpsertWithWhereUniqueWithoutClientInput = {
  where: Prisma.UsageLogWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.UsageLogUpdateWithoutClientInput,
    Prisma.UsageLogUncheckedUpdateWithoutClientInput
  >;
  create: Prisma.XOR<
    Prisma.UsageLogCreateWithoutClientInput,
    Prisma.UsageLogUncheckedCreateWithoutClientInput
  >;
};

export type UsageLogUpdateWithWhereUniqueWithoutClientInput = {
  where: Prisma.UsageLogWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.UsageLogUpdateWithoutClientInput,
    Prisma.UsageLogUncheckedUpdateWithoutClientInput
  >;
};

export type UsageLogUpdateManyWithWhereWithoutClientInput = {
  where: Prisma.UsageLogScalarWhereInput;
  data: Prisma.XOR<
    Prisma.UsageLogUpdateManyMutationInput,
    Prisma.UsageLogUncheckedUpdateManyWithoutClientInput
  >;
};

export type UsageLogScalarWhereInput = {
  AND?: Prisma.UsageLogScalarWhereInput | Prisma.UsageLogScalarWhereInput[];
  OR?: Prisma.UsageLogScalarWhereInput[];
  NOT?: Prisma.UsageLogScalarWhereInput | Prisma.UsageLogScalarWhereInput[];
  id?: Prisma.StringFilter<'UsageLog'> | string;
  reservationId?: Prisma.StringFilter<'UsageLog'> | string;
  clientId?: Prisma.StringFilter<'UsageLog'> | string;
  userId?: Prisma.StringFilter<'UsageLog'> | string;
  roomId?: Prisma.StringFilter<'UsageLog'> | string;
  scheduledStart?: Prisma.DateTimeFilter<'UsageLog'> | Date | string;
  scheduledEnd?: Prisma.DateTimeFilter<'UsageLog'> | Date | string;
  startTime?: Prisma.DateTimeFilter<'UsageLog'> | Date | string;
  endTime?: Prisma.DateTimeNullableFilter<'UsageLog'> | Date | string | null;
  scheduledMinutes?: Prisma.IntFilter<'UsageLog'> | number;
  actualConsumedMinutes?: Prisma.IntFilter<'UsageLog'> | number;
  billableMins?: Prisma.IntFilter<'UsageLog'> | number;
  overstayMinutes?: Prisma.IntFilter<'UsageLog'> | number;
  billingAmount?: Prisma.FloatFilter<'UsageLog'> | number;
  overstayed?: Prisma.BoolFilter<'UsageLog'> | boolean;
  createdAt?: Prisma.DateTimeFilter<'UsageLog'> | Date | string;
};

export type UsageLogCreateWithoutReservationInput = {
  id?: string;
  userId: string;
  roomId: string;
  scheduledStart: Date | string;
  scheduledEnd: Date | string;
  startTime: Date | string;
  endTime?: Date | string | null;
  scheduledMinutes: number;
  actualConsumedMinutes?: number;
  billableMins?: number;
  overstayMinutes?: number;
  billingAmount?: number;
  overstayed?: boolean;
  createdAt?: Date | string;
  client: Prisma.ClientCompanyCreateNestedOneWithoutUsageLogsInput;
};

export type UsageLogUncheckedCreateWithoutReservationInput = {
  id?: string;
  clientId: string;
  userId: string;
  roomId: string;
  scheduledStart: Date | string;
  scheduledEnd: Date | string;
  startTime: Date | string;
  endTime?: Date | string | null;
  scheduledMinutes: number;
  actualConsumedMinutes?: number;
  billableMins?: number;
  overstayMinutes?: number;
  billingAmount?: number;
  overstayed?: boolean;
  createdAt?: Date | string;
};

export type UsageLogCreateOrConnectWithoutReservationInput = {
  where: Prisma.UsageLogWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.UsageLogCreateWithoutReservationInput,
    Prisma.UsageLogUncheckedCreateWithoutReservationInput
  >;
};

export type UsageLogUpsertWithoutReservationInput = {
  update: Prisma.XOR<
    Prisma.UsageLogUpdateWithoutReservationInput,
    Prisma.UsageLogUncheckedUpdateWithoutReservationInput
  >;
  create: Prisma.XOR<
    Prisma.UsageLogCreateWithoutReservationInput,
    Prisma.UsageLogUncheckedCreateWithoutReservationInput
  >;
  where?: Prisma.UsageLogWhereInput;
};

export type UsageLogUpdateToOneWithWhereWithoutReservationInput = {
  where?: Prisma.UsageLogWhereInput;
  data: Prisma.XOR<
    Prisma.UsageLogUpdateWithoutReservationInput,
    Prisma.UsageLogUncheckedUpdateWithoutReservationInput
  >;
};

export type UsageLogUpdateWithoutReservationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  roomId?: Prisma.StringFieldUpdateOperationsInput | string;
  scheduledStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  scheduledEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  scheduledMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  actualConsumedMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billableMins?: Prisma.IntFieldUpdateOperationsInput | number;
  overstayMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billingAmount?: Prisma.FloatFieldUpdateOperationsInput | number;
  overstayed?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  client?: Prisma.ClientCompanyUpdateOneRequiredWithoutUsageLogsNestedInput;
};

export type UsageLogUncheckedUpdateWithoutReservationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  clientId?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  roomId?: Prisma.StringFieldUpdateOperationsInput | string;
  scheduledStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  scheduledEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  scheduledMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  actualConsumedMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billableMins?: Prisma.IntFieldUpdateOperationsInput | number;
  overstayMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billingAmount?: Prisma.FloatFieldUpdateOperationsInput | number;
  overstayed?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type UsageLogCreateManyClientInput = {
  id?: string;
  reservationId: string;
  userId: string;
  roomId: string;
  scheduledStart: Date | string;
  scheduledEnd: Date | string;
  startTime: Date | string;
  endTime?: Date | string | null;
  scheduledMinutes: number;
  actualConsumedMinutes?: number;
  billableMins?: number;
  overstayMinutes?: number;
  billingAmount?: number;
  overstayed?: boolean;
  createdAt?: Date | string;
};

export type UsageLogUpdateWithoutClientInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  roomId?: Prisma.StringFieldUpdateOperationsInput | string;
  scheduledStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  scheduledEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  scheduledMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  actualConsumedMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billableMins?: Prisma.IntFieldUpdateOperationsInput | number;
  overstayMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billingAmount?: Prisma.FloatFieldUpdateOperationsInput | number;
  overstayed?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  reservation?: Prisma.ReservationUpdateOneRequiredWithoutUsageLogNestedInput;
};

export type UsageLogUncheckedUpdateWithoutClientInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  reservationId?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  roomId?: Prisma.StringFieldUpdateOperationsInput | string;
  scheduledStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  scheduledEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  scheduledMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  actualConsumedMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billableMins?: Prisma.IntFieldUpdateOperationsInput | number;
  overstayMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billingAmount?: Prisma.FloatFieldUpdateOperationsInput | number;
  overstayed?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type UsageLogUncheckedUpdateManyWithoutClientInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  reservationId?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  roomId?: Prisma.StringFieldUpdateOperationsInput | string;
  scheduledStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  scheduledEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  scheduledMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  actualConsumedMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billableMins?: Prisma.IntFieldUpdateOperationsInput | number;
  overstayMinutes?: Prisma.IntFieldUpdateOperationsInput | number;
  billingAmount?: Prisma.FloatFieldUpdateOperationsInput | number;
  overstayed?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type UsageLogSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    reservationId?: boolean;
    clientId?: boolean;
    userId?: boolean;
    roomId?: boolean;
    scheduledStart?: boolean;
    scheduledEnd?: boolean;
    startTime?: boolean;
    endTime?: boolean;
    scheduledMinutes?: boolean;
    actualConsumedMinutes?: boolean;
    billableMins?: boolean;
    overstayMinutes?: boolean;
    billingAmount?: boolean;
    overstayed?: boolean;
    createdAt?: boolean;
    reservation?: boolean | Prisma.ReservationDefaultArgs<ExtArgs>;
    client?: boolean | Prisma.ClientCompanyDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['usageLog']
>;

export type UsageLogSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    reservationId?: boolean;
    clientId?: boolean;
    userId?: boolean;
    roomId?: boolean;
    scheduledStart?: boolean;
    scheduledEnd?: boolean;
    startTime?: boolean;
    endTime?: boolean;
    scheduledMinutes?: boolean;
    actualConsumedMinutes?: boolean;
    billableMins?: boolean;
    overstayMinutes?: boolean;
    billingAmount?: boolean;
    overstayed?: boolean;
    createdAt?: boolean;
    reservation?: boolean | Prisma.ReservationDefaultArgs<ExtArgs>;
    client?: boolean | Prisma.ClientCompanyDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['usageLog']
>;

export type UsageLogSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    reservationId?: boolean;
    clientId?: boolean;
    userId?: boolean;
    roomId?: boolean;
    scheduledStart?: boolean;
    scheduledEnd?: boolean;
    startTime?: boolean;
    endTime?: boolean;
    scheduledMinutes?: boolean;
    actualConsumedMinutes?: boolean;
    billableMins?: boolean;
    overstayMinutes?: boolean;
    billingAmount?: boolean;
    overstayed?: boolean;
    createdAt?: boolean;
    reservation?: boolean | Prisma.ReservationDefaultArgs<ExtArgs>;
    client?: boolean | Prisma.ClientCompanyDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['usageLog']
>;

export type UsageLogSelectScalar = {
  id?: boolean;
  reservationId?: boolean;
  clientId?: boolean;
  userId?: boolean;
  roomId?: boolean;
  scheduledStart?: boolean;
  scheduledEnd?: boolean;
  startTime?: boolean;
  endTime?: boolean;
  scheduledMinutes?: boolean;
  actualConsumedMinutes?: boolean;
  billableMins?: boolean;
  overstayMinutes?: boolean;
  billingAmount?: boolean;
  overstayed?: boolean;
  createdAt?: boolean;
};

export type UsageLogOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'reservationId'
  | 'clientId'
  | 'userId'
  | 'roomId'
  | 'scheduledStart'
  | 'scheduledEnd'
  | 'startTime'
  | 'endTime'
  | 'scheduledMinutes'
  | 'actualConsumedMinutes'
  | 'billableMins'
  | 'overstayMinutes'
  | 'billingAmount'
  | 'overstayed'
  | 'createdAt',
  ExtArgs['result']['usageLog']
>;
export type UsageLogInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  reservation?: boolean | Prisma.ReservationDefaultArgs<ExtArgs>;
  client?: boolean | Prisma.ClientCompanyDefaultArgs<ExtArgs>;
};
export type UsageLogIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  reservation?: boolean | Prisma.ReservationDefaultArgs<ExtArgs>;
  client?: boolean | Prisma.ClientCompanyDefaultArgs<ExtArgs>;
};
export type UsageLogIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  reservation?: boolean | Prisma.ReservationDefaultArgs<ExtArgs>;
  client?: boolean | Prisma.ClientCompanyDefaultArgs<ExtArgs>;
};

export type $UsageLogPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'UsageLog';
  objects: {
    reservation: Prisma.$ReservationPayload<ExtArgs>;
    client: Prisma.$ClientCompanyPayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      reservationId: string;
      clientId: string;
      userId: string;
      roomId: string;
      scheduledStart: Date;
      scheduledEnd: Date;
      startTime: Date;
      endTime: Date | null;
      scheduledMinutes: number;
      actualConsumedMinutes: number;
      billableMins: number;
      overstayMinutes: number;
      billingAmount: number;
      overstayed: boolean;
      createdAt: Date;
    },
    ExtArgs['result']['usageLog']
  >;
  composites: {};
};

export type UsageLogGetPayload<S extends boolean | null | undefined | UsageLogDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$UsageLogPayload, S>;

export type UsageLogCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<UsageLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: UsageLogCountAggregateInputType | true;
};

export interface UsageLogDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UsageLog']; meta: { name: 'UsageLog' } };
  /**
   * Find zero or one UsageLog that matches the filter.
   * @param {UsageLogFindUniqueArgs} args - Arguments to find a UsageLog
   * @example
   * // Get one UsageLog
   * const usageLog = await prisma.usageLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UsageLogFindUniqueArgs>(
    args: Prisma.SelectSubset<T, UsageLogFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__UsageLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$UsageLogPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one UsageLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UsageLogFindUniqueOrThrowArgs} args - Arguments to find a UsageLog
   * @example
   * // Get one UsageLog
   * const usageLog = await prisma.usageLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UsageLogFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, UsageLogFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__UsageLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$UsageLogPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first UsageLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsageLogFindFirstArgs} args - Arguments to find a UsageLog
   * @example
   * // Get one UsageLog
   * const usageLog = await prisma.usageLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UsageLogFindFirstArgs>(
    args?: Prisma.SelectSubset<T, UsageLogFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__UsageLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$UsageLogPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first UsageLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsageLogFindFirstOrThrowArgs} args - Arguments to find a UsageLog
   * @example
   * // Get one UsageLog
   * const usageLog = await prisma.usageLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UsageLogFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, UsageLogFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__UsageLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$UsageLogPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more UsageLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsageLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UsageLogs
   * const usageLogs = await prisma.usageLog.findMany()
   *
   * // Get first 10 UsageLogs
   * const usageLogs = await prisma.usageLog.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const usageLogWithIdOnly = await prisma.usageLog.findMany({ select: { id: true } })
   *
   */
  findMany<T extends UsageLogFindManyArgs>(
    args?: Prisma.SelectSubset<T, UsageLogFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$UsageLogPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >;

  /**
   * Create a UsageLog.
   * @param {UsageLogCreateArgs} args - Arguments to create a UsageLog.
   * @example
   * // Create one UsageLog
   * const UsageLog = await prisma.usageLog.create({
   *   data: {
   *     // ... data to create a UsageLog
   *   }
   * })
   *
   */
  create<T extends UsageLogCreateArgs>(
    args: Prisma.SelectSubset<T, UsageLogCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__UsageLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$UsageLogPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many UsageLogs.
   * @param {UsageLogCreateManyArgs} args - Arguments to create many UsageLogs.
   * @example
   * // Create many UsageLogs
   * const usageLog = await prisma.usageLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends UsageLogCreateManyArgs>(
    args?: Prisma.SelectSubset<T, UsageLogCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many UsageLogs and returns the data saved in the database.
   * @param {UsageLogCreateManyAndReturnArgs} args - Arguments to create many UsageLogs.
   * @example
   * // Create many UsageLogs
   * const usageLog = await prisma.usageLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many UsageLogs and only return the `id`
   * const usageLogWithIdOnly = await prisma.usageLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends UsageLogCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, UsageLogCreateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$UsageLogPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a UsageLog.
   * @param {UsageLogDeleteArgs} args - Arguments to delete one UsageLog.
   * @example
   * // Delete one UsageLog
   * const UsageLog = await prisma.usageLog.delete({
   *   where: {
   *     // ... filter to delete one UsageLog
   *   }
   * })
   *
   */
  delete<T extends UsageLogDeleteArgs>(
    args: Prisma.SelectSubset<T, UsageLogDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__UsageLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$UsageLogPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one UsageLog.
   * @param {UsageLogUpdateArgs} args - Arguments to update one UsageLog.
   * @example
   * // Update one UsageLog
   * const usageLog = await prisma.usageLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends UsageLogUpdateArgs>(
    args: Prisma.SelectSubset<T, UsageLogUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__UsageLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$UsageLogPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more UsageLogs.
   * @param {UsageLogDeleteManyArgs} args - Arguments to filter UsageLogs to delete.
   * @example
   * // Delete a few UsageLogs
   * const { count } = await prisma.usageLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends UsageLogDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, UsageLogDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more UsageLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsageLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UsageLogs
   * const usageLog = await prisma.usageLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends UsageLogUpdateManyArgs>(
    args: Prisma.SelectSubset<T, UsageLogUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more UsageLogs and returns the data updated in the database.
   * @param {UsageLogUpdateManyAndReturnArgs} args - Arguments to update many UsageLogs.
   * @example
   * // Update many UsageLogs
   * const usageLog = await prisma.usageLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more UsageLogs and only return the `id`
   * const usageLogWithIdOnly = await prisma.usageLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends UsageLogUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, UsageLogUpdateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$UsageLogPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one UsageLog.
   * @param {UsageLogUpsertArgs} args - Arguments to update or create a UsageLog.
   * @example
   * // Update or create a UsageLog
   * const usageLog = await prisma.usageLog.upsert({
   *   create: {
   *     // ... data to create a UsageLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UsageLog we want to update
   *   }
   * })
   */
  upsert<T extends UsageLogUpsertArgs>(
    args: Prisma.SelectSubset<T, UsageLogUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__UsageLogClient<
    runtime.Types.Result.GetResult<
      Prisma.$UsageLogPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of UsageLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsageLogCountArgs} args - Arguments to filter UsageLogs to count.
   * @example
   * // Count the number of UsageLogs
   * const count = await prisma.usageLog.count({
   *   where: {
   *     // ... the filter for the UsageLogs we want to count
   *   }
   * })
   **/
  count<T extends UsageLogCountArgs>(
    args?: Prisma.Subset<T, UsageLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UsageLogCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a UsageLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsageLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends UsageLogAggregateArgs>(
    args: Prisma.Subset<T, UsageLogAggregateArgs>,
  ): Prisma.PrismaPromise<GetUsageLogAggregateType<T>>;

  /**
   * Group by UsageLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsageLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends UsageLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends (Prisma.True extends HasSelectOrTake
      ? { orderBy: UsageLogGroupByArgs['orderBy'] }
      : { orderBy?: UsageLogGroupByArgs['orderBy'] }),
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends (T['by'] extends never[] ? Prisma.True : Prisma.False),
    InputErrors extends (ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]),
  >(
    args: Prisma.SubsetIntersection<T, UsageLogGroupByArgs, OrderByArg> & InputErrors,
  ): {} extends InputErrors ? GetUsageLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the UsageLog model
   */
  readonly fields: UsageLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UsageLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UsageLogClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  reservation<T extends Prisma.ReservationDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.ReservationDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__ReservationClient<
    | runtime.Types.Result.GetResult<
        Prisma.$ReservationPayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  client<T extends Prisma.ClientCompanyDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.ClientCompanyDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__ClientCompanyClient<
    | runtime.Types.Result.GetResult<
        Prisma.$ClientCompanyPayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the UsageLog model
 */
export interface UsageLogFieldRefs {
  readonly id: Prisma.FieldRef<'UsageLog', 'String'>;
  readonly reservationId: Prisma.FieldRef<'UsageLog', 'String'>;
  readonly clientId: Prisma.FieldRef<'UsageLog', 'String'>;
  readonly userId: Prisma.FieldRef<'UsageLog', 'String'>;
  readonly roomId: Prisma.FieldRef<'UsageLog', 'String'>;
  readonly scheduledStart: Prisma.FieldRef<'UsageLog', 'DateTime'>;
  readonly scheduledEnd: Prisma.FieldRef<'UsageLog', 'DateTime'>;
  readonly startTime: Prisma.FieldRef<'UsageLog', 'DateTime'>;
  readonly endTime: Prisma.FieldRef<'UsageLog', 'DateTime'>;
  readonly scheduledMinutes: Prisma.FieldRef<'UsageLog', 'Int'>;
  readonly actualConsumedMinutes: Prisma.FieldRef<'UsageLog', 'Int'>;
  readonly billableMins: Prisma.FieldRef<'UsageLog', 'Int'>;
  readonly overstayMinutes: Prisma.FieldRef<'UsageLog', 'Int'>;
  readonly billingAmount: Prisma.FieldRef<'UsageLog', 'Float'>;
  readonly overstayed: Prisma.FieldRef<'UsageLog', 'Boolean'>;
  readonly createdAt: Prisma.FieldRef<'UsageLog', 'DateTime'>;
}

// Custom InputTypes
/**
 * UsageLog findUnique
 */
export type UsageLogFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UsageLog
   */
  select?: Prisma.UsageLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UsageLog
   */
  omit?: Prisma.UsageLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsageLogInclude<ExtArgs> | null;
  /**
   * Filter, which UsageLog to fetch.
   */
  where: Prisma.UsageLogWhereUniqueInput;
};

/**
 * UsageLog findUniqueOrThrow
 */
export type UsageLogFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UsageLog
   */
  select?: Prisma.UsageLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UsageLog
   */
  omit?: Prisma.UsageLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsageLogInclude<ExtArgs> | null;
  /**
   * Filter, which UsageLog to fetch.
   */
  where: Prisma.UsageLogWhereUniqueInput;
};

/**
 * UsageLog findFirst
 */
export type UsageLogFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UsageLog
   */
  select?: Prisma.UsageLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UsageLog
   */
  omit?: Prisma.UsageLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsageLogInclude<ExtArgs> | null;
  /**
   * Filter, which UsageLog to fetch.
   */
  where?: Prisma.UsageLogWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UsageLogs to fetch.
   */
  orderBy?: Prisma.UsageLogOrderByWithRelationInput | Prisma.UsageLogOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for UsageLogs.
   */
  cursor?: Prisma.UsageLogWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UsageLogs from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UsageLogs.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of UsageLogs.
   */
  distinct?: Prisma.UsageLogScalarFieldEnum | Prisma.UsageLogScalarFieldEnum[];
};

/**
 * UsageLog findFirstOrThrow
 */
export type UsageLogFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UsageLog
   */
  select?: Prisma.UsageLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UsageLog
   */
  omit?: Prisma.UsageLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsageLogInclude<ExtArgs> | null;
  /**
   * Filter, which UsageLog to fetch.
   */
  where?: Prisma.UsageLogWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UsageLogs to fetch.
   */
  orderBy?: Prisma.UsageLogOrderByWithRelationInput | Prisma.UsageLogOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for UsageLogs.
   */
  cursor?: Prisma.UsageLogWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UsageLogs from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UsageLogs.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of UsageLogs.
   */
  distinct?: Prisma.UsageLogScalarFieldEnum | Prisma.UsageLogScalarFieldEnum[];
};

/**
 * UsageLog findMany
 */
export type UsageLogFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UsageLog
   */
  select?: Prisma.UsageLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UsageLog
   */
  omit?: Prisma.UsageLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsageLogInclude<ExtArgs> | null;
  /**
   * Filter, which UsageLogs to fetch.
   */
  where?: Prisma.UsageLogWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UsageLogs to fetch.
   */
  orderBy?: Prisma.UsageLogOrderByWithRelationInput | Prisma.UsageLogOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing UsageLogs.
   */
  cursor?: Prisma.UsageLogWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UsageLogs from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UsageLogs.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of UsageLogs.
   */
  distinct?: Prisma.UsageLogScalarFieldEnum | Prisma.UsageLogScalarFieldEnum[];
};

/**
 * UsageLog create
 */
export type UsageLogCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UsageLog
   */
  select?: Prisma.UsageLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UsageLog
   */
  omit?: Prisma.UsageLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsageLogInclude<ExtArgs> | null;
  /**
   * The data needed to create a UsageLog.
   */
  data: Prisma.XOR<Prisma.UsageLogCreateInput, Prisma.UsageLogUncheckedCreateInput>;
};

/**
 * UsageLog createMany
 */
export type UsageLogCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many UsageLogs.
   */
  data: Prisma.UsageLogCreateManyInput | Prisma.UsageLogCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * UsageLog createManyAndReturn
 */
export type UsageLogCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UsageLog
   */
  select?: Prisma.UsageLogSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the UsageLog
   */
  omit?: Prisma.UsageLogOmit<ExtArgs> | null;
  /**
   * The data used to create many UsageLogs.
   */
  data: Prisma.UsageLogCreateManyInput | Prisma.UsageLogCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsageLogIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * UsageLog update
 */
export type UsageLogUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UsageLog
   */
  select?: Prisma.UsageLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UsageLog
   */
  omit?: Prisma.UsageLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsageLogInclude<ExtArgs> | null;
  /**
   * The data needed to update a UsageLog.
   */
  data: Prisma.XOR<Prisma.UsageLogUpdateInput, Prisma.UsageLogUncheckedUpdateInput>;
  /**
   * Choose, which UsageLog to update.
   */
  where: Prisma.UsageLogWhereUniqueInput;
};

/**
 * UsageLog updateMany
 */
export type UsageLogUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update UsageLogs.
   */
  data: Prisma.XOR<Prisma.UsageLogUpdateManyMutationInput, Prisma.UsageLogUncheckedUpdateManyInput>;
  /**
   * Filter which UsageLogs to update
   */
  where?: Prisma.UsageLogWhereInput;
  /**
   * Limit how many UsageLogs to update.
   */
  limit?: number;
};

/**
 * UsageLog updateManyAndReturn
 */
export type UsageLogUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UsageLog
   */
  select?: Prisma.UsageLogSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the UsageLog
   */
  omit?: Prisma.UsageLogOmit<ExtArgs> | null;
  /**
   * The data used to update UsageLogs.
   */
  data: Prisma.XOR<Prisma.UsageLogUpdateManyMutationInput, Prisma.UsageLogUncheckedUpdateManyInput>;
  /**
   * Filter which UsageLogs to update
   */
  where?: Prisma.UsageLogWhereInput;
  /**
   * Limit how many UsageLogs to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsageLogIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * UsageLog upsert
 */
export type UsageLogUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UsageLog
   */
  select?: Prisma.UsageLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UsageLog
   */
  omit?: Prisma.UsageLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsageLogInclude<ExtArgs> | null;
  /**
   * The filter to search for the UsageLog to update in case it exists.
   */
  where: Prisma.UsageLogWhereUniqueInput;
  /**
   * In case the UsageLog found by the `where` argument doesn't exist, create a new UsageLog with this data.
   */
  create: Prisma.XOR<Prisma.UsageLogCreateInput, Prisma.UsageLogUncheckedCreateInput>;
  /**
   * In case the UsageLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UsageLogUpdateInput, Prisma.UsageLogUncheckedUpdateInput>;
};

/**
 * UsageLog delete
 */
export type UsageLogDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UsageLog
   */
  select?: Prisma.UsageLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UsageLog
   */
  omit?: Prisma.UsageLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsageLogInclude<ExtArgs> | null;
  /**
   * Filter which UsageLog to delete.
   */
  where: Prisma.UsageLogWhereUniqueInput;
};

/**
 * UsageLog deleteMany
 */
export type UsageLogDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which UsageLogs to delete
   */
  where?: Prisma.UsageLogWhereInput;
  /**
   * Limit how many UsageLogs to delete.
   */
  limit?: number;
};

/**
 * UsageLog without action
 */
export type UsageLogDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UsageLog
   */
  select?: Prisma.UsageLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UsageLog
   */
  omit?: Prisma.UsageLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsageLogInclude<ExtArgs> | null;
};
